// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Andrew Yates
//
// REGEX SCAN OVER A SCROLLBACK-SHAPED CORPUS.
//
// WHY THIS EXISTS: aterm-regex shipped with no bench target, and nothing
// anywhere in the tree reached the Pike VM under measurement. The numbers in
// lib.rs's module docs were hand-run once and never re-run, so the engine's
// per-keystroke cost in the find bar was an unmeasured quantity — which is how
// `^ERROR` came to walk every byte of the scrollback to prove it could not
// match anywhere but offset 0.
//
// THE CORPUS IS THE SHIPPED DEFAULT, not a round number: 100_000 rows, which is
// both `scrollback_lines` (aterm-gui prefs) and `DEFAULT_MAX_CACHED_LINES`
// (aterm-search). The find bar has no debounce and regex mode explicitly opts
// out of the narrowing fast path (`Regex has no prefix-subset property`), so one
// keystroke is one full pass over all of it. Rows are generated by a
// deterministic LCG into shapes a terminal actually holds — prompts, cargo
// output, log lines, paths — averaging ~79 bytes.
//
// THE LANES ARE TWO-SIDED. Three reach the anchor fast path and three provably
// do not, and `verify_reaches_target` asserts that split *behaviourally*,
// through the public step budget, rather than by reading a private flag:
//
//   * `anchored_miss`     — `(?i)^ERROR`, the default (`search_sticky_case` is
//                           false, so `compile_regex` prefixes `(?i)`). Almost
//                           no row starts with it. THE WIN.
//   * `anchored_class`    — `(?i)^\d+`, a class-led anchor. Widest lead-byte
//                           set, so the old prefilter skipped least.
//   * `anchored_hit`      — `^\[`, which many rows DO start with. Guards the
//                           other side: the fast path must not cost a match.
//   * `unanchored`        — `(?i)ERROR`. CONTROL. Must not move.
//   * `multiline`         — `(?im)^ERROR`. CONTROL, and the one that matters
//                           most: `(?m)^` is `StartLine`, satisfied after every
//                           newline, so it anchors nothing and must keep its
//                           prefilter.
//   * `word_boundary`     — `\bcommit`. CONTROL. The other shape lib.rs names
//                           as what a terminal actually searches for.
//   * `rare_lead`         — `(?i)QUARK`. THE COST MODEL, stated as a
//                           measurement. Same shape and length as `unanchored`
//                           and the same corpus; only the lead byte's rarity
//                           differs. The gap between the two IS the
//                           candidate-hunting cost — what the prefilter spends
//                           entering the simulation at positions that die on
//                           their second character — so it bounds what any
//                           improvement to the filter can possibly return, and
//                           it is the reason the second-byte filter exists.
//
//   cargo bench -p aterm-regex --bench anchored_scan

use aterm_regex::{Regex, RegexBuilder};
use criterion::{BenchmarkId, Criterion, Throughput, black_box, criterion_group, criterion_main};

/// `scrollback_lines` and `DEFAULT_MAX_CACHED_LINES` both default to this.
const ROWS: usize = 100_000;

/// Deterministic, so the corpus is the same on every box and every run.
struct Lcg(u64);

impl Lcg {
    fn next(&mut self) -> u64 {
        self.0 = self
            .0
            .wrapping_mul(6_364_136_223_846_793_005)
            .wrapping_add(1);
        self.0 >> 11
    }

    fn pick<'a>(&mut self, from: &[&'a str]) -> &'a str {
        let i = usize::try_from(self.next()).unwrap_or(0) % from.len();
        from[i]
    }
}

/// Rows shaped like what a terminal actually holds after a build and a test run.
///
/// The mix matters to the measurement in one specific way: how often the lead
/// byte of an anchored pattern appears *somewhere* in a row decides how much
/// work the old prefilter did before failing the `\A` assertion. `E`/`e` and the
/// digits are deliberately common here because they are common in real output —
/// making the old path's cost representative rather than a worst case.
fn corpus() -> Vec<String> {
    let mut lcg = Lcg(0x5DEE_CE66_D5DE);
    let templates: &[&str] = &[
        "   Compiling aterm-render v0.1.0 (/Users//dev/aterm/crates/aterm-render)",
        "warning: unused variable: `expected` at crates/aterm-core/src/grid.rs:118:9",
        "test terminal::render_cells::tests::damage_scope_retains_rows ... ok",
        "[2026-08-28T10:14:22Z INFO  aterm_gui::app_render] frame 41204 in 3.1ms",
        "$ cargo test -p aterm-search --lib -- --nocapture",
        "  --> crates/aterm-effects/src/word_decorations.rs:2291:33",
        "error[E0308]: mismatched types, expected `usize`, found `u32`",
        "drwxr-xr-x  12 dev  staff   384 Aug 28 09:41 crates/aterm-regex/src",
        "1723 packets transmitted, 1723 received, 0% packet loss, time 1721ms",
        "ERROR failed to open /var/db/aterm/index.sqlite: permission denied",
        "note: run with `RUST_BACKTRACE=1` to display a backtrace",
        "        at aterm_core::terminal::Terminal::feed (terminal/mod.rs:9412)",
    ];
    (0..ROWS)
        .map(|i| {
            let base = lcg.pick(templates);
            // A little variation so the rows are not 12 repeated strings sitting
            // in one cache line for the whole scan.
            format!("{base} #{i}")
        })
        .collect()
}

fn build(pattern: &str) -> Regex {
    RegexBuilder::new(pattern)
        .build()
        .unwrap_or_else(|e| panic!("{pattern} must compile: {e}"))
}

/// Every lane is one full pass over the corpus, which is one keystroke.
fn scan(re: &Regex, rows: &[String]) -> usize {
    rows.iter().filter(|row| re.is_match(row)).count()
}

/// THE REACH GUARD, and it is two-sided by construction.
///
/// A start-anchored program answers "no match" in a couple of steps whatever the
/// row's length; an unanchored one has to walk it. So a step budget of 64 — far
/// under the ~600 a 600-byte row costs to walk — separates them cleanly: the
/// anchored patterns must ANSWER inside it and the controls must be REFUSED by
/// it. Before the anchor fast path existed, every one of these was refused.
///
/// This is deliberately behavioural. Asserting on a private `start_anchored`
/// flag would prove the flag was set, not that the search consulted it; the
/// budget is charged inside the loop the optimization removes, so only the real
/// path can satisfy it.
fn verify_reaches_target(rows: &[String]) {
    // A long row with no match, so the walk is the whole thing.
    let row: &str = rows
        .iter()
        .map(String::as_str)
        .find(|r| r.len() > 60 && !r.starts_with('E'))
        .expect("the corpus holds a long non-matching row");

    for pattern in ["(?i)^ERROR", r"(?i)^\d+", r"^\["] {
        let re = RegexBuilder::new(pattern)
            .step_limit(64)
            .build()
            .expect("compiles");
        assert!(
            re.try_is_match(row).is_ok(),
            "{pattern} must answer without walking the row — the anchor fast \
             path is not reached, so this bench measures nothing",
        );
    }
    for pattern in ["(?i)ERROR", "(?im)^ERROR", r"\bcommit"] {
        let re = RegexBuilder::new(pattern)
            .step_limit(64)
            .build()
            .expect("compiles");
        assert!(
            re.try_is_match(row).is_err(),
            "{pattern} must still walk the row — it is a CONTROL, and if the \
             anchor fast path has swallowed it the optimization is wrong, not \
             fast",
        );
    }

    // And the fast path must not cost a match: `^\[` really does hit.
    let hits = scan(&build(r"^\["), rows);
    assert!(hits > 0, "the anchored_hit lane must actually match rows");
}

fn bench(c: &mut Criterion) {
    let rows = corpus();
    verify_reaches_target(&rows);
    let bytes: u64 = rows.iter().map(|r| r.len() as u64).sum();

    let mut group = c.benchmark_group("scrollback_scan");
    group.throughput(Throughput::Bytes(bytes));
    for (lane, pattern) in [
        ("anchored_miss", "(?i)^ERROR"),
        ("anchored_class", r"(?i)^\d+"),
        ("anchored_hit", r"^\["),
        ("unanchored", "(?i)ERROR"),
        ("multiline", "(?im)^ERROR"),
        ("word_boundary", r"\bcommit"),
        ("rare_lead", "(?i)QUARK"),
    ] {
        let re = build(pattern);
        group.bench_with_input(BenchmarkId::from_parameter(lane), &re, |b, re| {
            b.iter(|| black_box(scan(re, &rows)));
        });
    }
    group.finish();
}

criterion_group!(benches, bench);
criterion_main!(benches);
