// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Andrew Yates

//! GENERATE A WALK PACE TABLE for a window of the arc, by the rule the
//! shipped one was generated by: equal composited step per knot, the step
//! being the bed under the letters plus the vivid rail below the row.
//!
//! `pacegen <lut0> <lut1> [knots]` prints the `u16` knots.
use aterm_effects::rainbow_kitty::ribbon::{bed_ink, bed_luma_budget, rail_ink};
use aterm_effects::spectrum::{SPECTRUM_LUT_LEN, spectrum};

const NORD_FG: u32 = 0x00D8_DEE9;

fn s2l(v: f32) -> f32 {
    let v = v / 255.0;
    if v <= 0.04045 {
        v / 12.92
    } else {
        ((v + 0.055) / 1.055).powf(2.4)
    }
}
fn lab(c: u32) -> (f32, f32, f32) {
    let ch = |sh: u32| ((c >> sh) & 0xff) as f32;
    let (r, g, b) = (s2l(ch(16)), s2l(ch(8)), s2l(ch(0)));
    let (x, y, z) = (
        0.4124 * r + 0.3576 * g + 0.1805 * b,
        0.2126 * r + 0.7152 * g + 0.0722 * b,
        0.0193 * r + 0.1192 * g + 0.9505 * b,
    );
    let f = |t: f32| {
        if t > 0.008_856 {
            t.cbrt()
        } else {
            7.787 * t + 16.0 / 116.0
        }
    };
    let (fx, fy, fz) = (f(x / 0.95047), f(y), f(z / 1.08883));
    (116.0 * fy - 16.0, 500.0 * (fx - fy), 200.0 * (fy - fz))
}
fn de(a: u32, b: u32) -> f32 {
    let (l1, a1, b1) = lab(a);
    let (l2, a2, b2) = lab(b);
    ((l1 - l2).powi(2) + (a1 - a2).powi(2) + (b1 - b2).powi(2)).sqrt()
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let lut0: usize = args[1].parse().unwrap();
    let lut1: usize = args[2].parse().unwrap();
    let knots: usize = args.get(3).map_or(65, |s| s.parse().unwrap());
    let budget = bed_luma_budget(NORD_FG);
    let span = (SPECTRUM_LUT_LEN - 1) as f32;
    let (w0, w1) = (lut0 as f32 / span, lut1 as f32 / span);
    const N: usize = 4096;
    let step = |a: f32, b: f32| {
        de(bed_ink(spectrum(a), budget), bed_ink(spectrum(b), budget))
            + de(rail_ink(spectrum(a)), rail_ink(spectrum(b)))
    };
    let mut cum = vec![0.0f32; N + 1];
    for i in 1..=N {
        let a = w0 + (w1 - w0) * (i - 1) as f32 / N as f32;
        let b = w0 + (w1 - w0) * i as f32 / N as f32;
        cum[i] = cum[i - 1] + step(a, b).max(0.005);
    }
    let total = cum[N];
    let mut out = Vec::with_capacity(knots);
    let mut j = 0usize;
    for k in 0..knots {
        let want = k as f32 / (knots - 1) as f32 * total;
        while j < N && cum[j + 1] < want {
            j += 1;
        }
        let sp = (cum[j + 1] - cum[j]).max(1e-9);
        let f = ((want - cum[j]) / sp).clamp(0.0, 1.0);
        let a = w0 + (w1 - w0) * (j as f32 + f) / N as f32;
        out.push((a * 65535.0).round().clamp(0.0, 65535.0) as u16);
    }
    // The ends are exact by construction.
    out[0] = (w0 * 65535.0).round() as u16;
    out[knots - 1] = (w1 * 65535.0).round() as u16;
    println!("// window entries {lut0}..={lut1}, {knots} knots, total step {total:.1}");
    for chunk in out.chunks(13) {
        println!(
            "    {}",
            chunk
                .iter()
                .map(|v| format!("{v},"))
                .collect::<Vec<_>>()
                .join(" ")
        );
    }
}
