// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Andrew Yates

//! aterm's clock — `std::time` everywhere it exists, and a browser clock where
//! it does not.
//!
//! # Why this crate exists
//!
//! `std::time::Instant::now()` PANICS on `wasm32-unknown-unknown` ("time not
//! implemented on this platform"): the target has no clock syscall, and the
//! browser's clocks are JS functions. The engine samples a monotonic clock
//! everywhere — the VT processing loop, the effects tick, the predictive-echo
//! ledger, the present pacing — so a terminal compiled to wasm would trap on
//! its first frame.
//!
//! # The shape of the fix
//!
//! On every target that HAS `std::time`, this module is a re-export and
//! nothing else. There is no wrapper type, no conversion, no `#[inline]` to
//! hope the optimizer honours: [`Instant`] IS `std::time::Instant`, so the
//! native engine is byte-identical to one written against `std` directly and
//! this crate compiles to nothing.
//!
//! On `wasm32-unknown-unknown` — the ONE target in this workspace that has no
//! `std::time` — it swaps in an [`Instant`] over `performance.now()` (monotonic,
//! sub-millisecond, and the browser's own definition of "since this document's
//! time origin") and a [`SystemTime`] over `Date.now()` (wall clock, ms since
//! the Unix epoch). [`Duration`] is `core::time::Duration` on both arms —
//! duration arithmetic has never needed a platform.
//!
//! # Precision, on the wasm arm
//!
//! `performance.now()` and `Date.now()` both return `f64` milliseconds.
//! Converting through `Duration::from_secs_f64` would inherit that method's
//! panics on a negative or non-finite input, and a browser is not obliged to
//! hand back a sane number: cross-origin isolation, clock clamping for Spectre
//! mitigation and a suspended tab all perturb it. So the conversion is explicit
//! and total — non-finite and negative both floor to zero — and it splits whole
//! milliseconds from the fraction before scaling, so a multi-hour-old time
//! origin keeps sub-microsecond resolution instead of spending the mantissa on
//! the integer part.
//!
//! # How the wasm arm is tested without running a browser
//!
//! The Trust toolchain has no `wasm32` std, so the wasm arm is cross-compiled
//! on upstream stable: `cargo xtask gate web` does exactly that, and since
//! 2026-08-31 it FAILS when these crates stop building instead of reading its
//! own `can't find crate for std` back as a skip. What a cross-compile still
//! cannot do is RUN the module, and that is what the rest of this section is
//! about. The shim is written so that everything except two `extern`
//! declarations and the two one-line `now()` bodies is target-independent, and
//! it is compiled into the NATIVE test build: the millisecond conversion, the
//! saturating differences, the checked arithmetic and the backwards-clock error
//! are all driven by ordinary `cargo test` on this machine.

// A clock is a leaf: no allocation tricks, no platform pointers, nothing to
// justify an escape hatch. The wasm arm's JS bindings are generated by
// wasm-bindgen, which emits its own (audited) unsafe.
#![cfg_attr(
    not(all(target_arch = "wasm32", target_os = "unknown")),
    forbid(unsafe_code)
)]

/// A span of time, platform-independent. Identical on every target — this is
/// `core::time::Duration`, re-exported so callers need only one import.
pub use core::time::Duration;

// The arm predicate is `wasm32-unknown-unknown` EXACTLY, not `target_arch =
// "wasm32"`. `wasm32-wasip1` and `wasm32-unknown-emscripten` are wasm targets
// that DO have a working `std::time`, and handing them the browser shim would
// bind `performance.now()` in a runtime that has no `performance` object. This
// is the predicate the retired `web-time` keyed on, and it is what makes this
// crate's headline claim — `std::time` on every target that HAS `std::time` —
// literally true rather than approximately true.
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
mod native {
    /// The platform monotonic clock — `std::time::Instant` itself.
    pub use std::time::Instant;
    /// The platform wall clock — `std::time::SystemTime` itself.
    pub use std::time::{SystemTime, SystemTimeError, UNIX_EPOCH};
}

#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub use native::{Instant, SystemTime, SystemTimeError, UNIX_EPOCH};

// The browser clock. Compiled into the NATIVE test build as well
// (`cfg(test)`): `cargo xtask gate web` cross-compiles this module on upstream
// stable, but a compile check executes nothing, so a browser-only module would
// still be code no local TEST could reach. See `shim`'s own docs.
#[cfg(any(all(target_arch = "wasm32", target_os = "unknown"), test))]
mod shim;

#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
pub use shim::{Instant, SystemTime, SystemTimeError, UNIX_EPOCH};

#[cfg(test)]
mod tests {
    use super::{Duration, Instant, SystemTime, UNIX_EPOCH};

    /// The monotonic clock moves forward and never backward across a sleep.
    #[test]
    fn instant_is_monotonic_across_a_sleep() {
        let t0 = Instant::now();
        std::thread::sleep(Duration::from_millis(5));
        let t1 = Instant::now();
        assert!(t1 >= t0, "clock went backwards");
        assert!(
            t1.duration_since(t0) >= Duration::from_millis(4),
            "a 5ms sleep measured as {:?}",
            t1.duration_since(t0)
        );
    }

    /// `duration_since` on a LATER instant saturates to zero rather than
    /// panicking — the contract `std` has had since 1.60 and the one every
    /// caller in the workspace relies on.
    #[test]
    fn duration_since_saturates_rather_than_panicking() {
        let t0 = Instant::now();
        std::thread::sleep(Duration::from_millis(2));
        let t1 = Instant::now();
        assert_eq!(t0.duration_since(t1), Duration::ZERO);
        assert_eq!(t0.checked_duration_since(t1), None);
        assert_eq!(t0.saturating_duration_since(t1), Duration::ZERO);
    }

    /// Duration arithmetic round-trips through the instant.
    #[test]
    fn instant_duration_arithmetic_round_trips() {
        let t0 = Instant::now();
        let t1 = t0 + Duration::from_secs(3);
        assert_eq!(t1 - t0, Duration::from_secs(3));
        assert_eq!(t1 - Duration::from_secs(3), t0);
        assert!(t1 > t0);
    }

    /// The wall clock is anchored at the Unix epoch and is plausibly "now" —
    /// after 2020 and before 2200, which is all a clock shim can honestly
    /// promise.
    #[test]
    fn system_time_is_anchored_at_the_unix_epoch() {
        let since = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("wall clock is at or after the Unix epoch");
        assert!(
            since.as_secs() > 1_577_836_800,
            "wall clock reads before 2020: {since:?}"
        );
        assert!(
            since.as_secs() < 7_258_118_400,
            "wall clock reads after 2200: {since:?}"
        );
    }
}
