// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Andrew Yates
//
// DEFLATE / zlib DECOMPRESSION (ROADMAP WS-K).
//
// WHY THIS EXISTS: aterm-codec had no bench target at all, and no bench anywhere
// in the tree reached `inflate`. gpu_frame.rs / image_diff.rs feed their inline
// image once during setup, outside `b.iter`, and they use OSC 1337 base64, which
// is uncompressed — so the Kitty-graphics `o=z` path (APC transmission with
// RFC 1950 zlib, `build_kitty_image` -> `zlib_decompress`) was entirely
// unmeasured. The in-code note at the adler32 NMAX fix records the shape of the
// workload: a 4 MiB Kitty `o=z` payload, ~6.6 ms in `zlib_decompress` of which
// ~5.4 ms is inflate proper.
//
// THE CORPUS IS GENERATED BY A DEFLATE ENCODER IN THIS FILE. The crate has zero
// dependencies by policy, so there is no compressor to lean on; a hand-written
// LSB-first bit writer plus a canonical Huffman assignment emits real BTYPE=1
// (fixed) and BTYPE=2 (dynamic) blocks. That is not a shortcut, it is the point:
// the encoder CHOOSES the code lengths, so the bench knows exactly how many of
// the emitted symbols have codes short enough for a root-table lookup and how
// many must take the bit-at-a-time fallback. `verify_reaches_target` asserts
// that split, and asserts every lane round-trips to the exact source bytes — if
// the encoder were wrong, the bench would fail rather than quietly measure a
// stream that errors out after four symbols.
//
// THE LANES BRACKET THE ROOT TABLE:
//   * `fixed_1mib`    — BTYPE=1. The fixed literal/length code's longest word is
//                       9 bits, so EVERY symbol resolves in the table. Upper
//                       bound of the win.
//   * `dynamic_4mib`  — BTYPE=2 with code lengths spanning 3..13 bits, tuned so
//                       roughly two thirds of emitted symbols are table hits and
//                       the rest take the fallback. The realistic case.
//   * `tiny_dynamic_blocks` — THE REGRESSION CHECK, and the reason this lane
//                       exists at all: a table-driven decoder pays a per-table
//                       BUILD cost that the bit-at-a-time decoder does not.
//                       Hundreds of tiny dynamic blocks maximise table builds
//                       per decoded symbol. If a table costs more than it saves
//                       anywhere, it is here.
//
//   cargo bench -p aterm-codec --bench inflate_zlib

use aterm_codec::inflate::zlib_decompress;
use criterion::{BenchmarkId, Criterion, Throughput, black_box, criterion_group, criterion_main};

/// Root bits of the decoder's flat lookup table. Mirrored from
/// `inflate.rs::ROOT_BITS` (private) so the reach assertions can name the same
/// boundary the code under test branches on. If the two ever drift, the reach
/// assertions below become wrong rather than merely stale — hence the explicit
/// hit-fraction bounds, which would fail loudly.
const ROOT_BITS: u16 = 9;

// RFC 1951 3.2.5 tables, restated here because they are private to the decoder.
const LENGTH_BASE: [u16; 29] = [
    3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 17, 19, 23, 27, 31, 35, 43, 51, 59, 67, 83, 99, 115, 131,
    163, 195, 227, 258,
];
const LENGTH_EXTRA: [u32; 29] = [
    0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0,
];
const DIST_BASE: [u16; 30] = [
    1, 2, 3, 4, 5, 7, 9, 13, 17, 25, 33, 49, 65, 97, 129, 193, 257, 385, 513, 769, 1025, 1537,
    2049, 3073, 4097, 6145, 8193, 12289, 16385, 24577,
];
const DIST_EXTRA: [u32; 30] = [
    0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13,
    13,
];
const CLCL_ORDER: [usize; 19] = [
    16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15,
];

// ---------------------------------------------------------------------------
// LSB-first bit writer (DEFLATE bit order)
// ---------------------------------------------------------------------------

struct BitWriter {
    out: Vec<u8>,
    acc: u32,
    nbits: u32,
}

impl BitWriter {
    fn empty() -> Self {
        Self {
            out: Vec::new(),
            acc: 0,
            nbits: 0,
        }
    }

    /// Write `n` low bits of `v`, least-significant bit first — the order
    /// DEFLATE uses for header fields and for the extra bits of length/distance
    /// codes.
    fn bits_lsb(&mut self, v: u32, n: u32) {
        for i in 0..n {
            self.acc |= ((v >> i) & 1) << self.nbits;
            self.nbits += 1;
            if self.nbits == 8 {
                self.flush_byte();
            }
        }
    }

    /// Write a Huffman code word: `n` bits of `v`, MOST-significant bit first.
    /// RFC 1951 3.1.1 — Huffman codes are packed starting with the MSB even
    /// though everything else in the format is LSB-first.
    fn code_msb(&mut self, v: u32, n: u32) {
        for i in (0..n).rev() {
            self.acc |= ((v >> i) & 1) << self.nbits;
            self.nbits += 1;
            if self.nbits == 8 {
                self.flush_byte();
            }
        }
    }

    fn flush_byte(&mut self) {
        self.out.push((self.acc & 0xff) as u8);
        self.acc = 0;
        self.nbits = 0;
    }

    fn finish(mut self) -> Vec<u8> {
        if self.nbits > 0 {
            self.flush_byte();
        }
        self.out
    }
}

// ---------------------------------------------------------------------------
// Canonical Huffman code assignment
// ---------------------------------------------------------------------------

/// A canonical prefix code: `(code, length)` per symbol, length 0 = unused.
#[derive(Clone)]
struct CanonCode {
    lengths: Vec<u16>,
    codes: Vec<u32>,
}

impl CanonCode {
    /// Assign canonical code words to `lengths` (RFC 1951 3.2.2), asserting the
    /// set is a COMPLETE prefix code. Completeness is not optional: the decoder
    /// rejects an incomplete literal/length code outright, so a wrong tier spec
    /// must fail here, in setup, not silently produce a stream that errors.
    fn build(lengths: Vec<u16>) -> Self {
        let maxbits = 15usize;
        let mut count = vec![0u32; maxbits + 2];
        for &l in &lengths {
            assert!(l as usize <= maxbits, "code length {l} exceeds MAXBITS");
            if l != 0 {
                count[l as usize] += 1;
            }
        }
        // Kraft sum, in units of 2^-maxbits so it is exact integer arithmetic.
        let kraft: u64 = (1..=maxbits)
            .map(|l| u64::from(count[l]) << (maxbits - l))
            .sum();
        assert_eq!(
            kraft,
            1u64 << maxbits,
            "code is not complete (Kraft {kraft} vs {})",
            1u64 << maxbits
        );
        let mut next = vec![0u32; maxbits + 2];
        let mut code = 0u32;
        for l in 1..=maxbits {
            code = (code + count[l - 1]) << 1;
            next[l] = code;
        }
        let mut codes = vec![0u32; lengths.len()];
        for (sym, &l) in lengths.iter().enumerate() {
            if l != 0 {
                codes[sym] = next[l as usize];
                next[l as usize] += 1;
            }
        }
        Self { lengths, codes }
    }

    fn put(&self, w: &mut BitWriter, sym: usize) {
        let len = u32::from(self.lengths[sym]);
        assert!(len != 0, "symbol {sym} has no code");
        w.code_msb(self.codes[sym], len);
    }
}

/// Build a length vector of `total` symbols from `(count, length)` tiers,
/// handing the SHORTEST codes to the symbols that appear earliest in
/// `priority`. The tiers are the whole design of a lane: they decide how many
/// emitted symbols land in the root table and how many fall back.
fn lengths_from_tiers(total: usize, tiers: &[(usize, u16)], priority: &[usize]) -> Vec<u16> {
    let mut lengths = vec![0u16; total];
    let mut sorted: Vec<(usize, u16)> = tiers.to_vec();
    sorted.sort_by_key(|&(_, len)| len);
    let mut it = priority.iter();
    for (count, len) in sorted {
        for _ in 0..count {
            let sym = *it.next().expect("priority list shorter than the tier spec");
            lengths[sym] = len;
        }
    }
    assert!(
        it.next().is_none(),
        "priority list longer than the tier spec"
    );
    lengths
}

// ---------------------------------------------------------------------------
// Token stream: literals and matches, generated together with their output
// ---------------------------------------------------------------------------

#[derive(Clone, Copy)]
enum Token {
    Literal(u8),
    /// `(length, distance)` — always consistent with the bytes already emitted,
    /// because the generator appends the matched bytes as it records the token.
    Match(u16, u16),
}

/// Deterministic LCG, so a run is reproducible and the corpus is stable across
/// the two arms of an A/B.
struct Lcg(u64);

impl Lcg {
    fn next(&mut self) -> u32 {
        self.0 = self
            .0
            .wrapping_mul(6_364_136_223_846_793_005)
            .wrapping_add(1_442_695_040_888_963_407);
        (self.0 >> 33) as u32
    }
}

/// Generate `target` bytes of "image-like" output together with the token
/// stream that reproduces it exactly. `hot_share` is the percentage of literals
/// drawn from the 62 byte values the dynamic lane gives short codes to; it is
/// the knob that sets the table-hit fraction.
fn generate(target: usize, hot_share: u32, seed: u64) -> (Vec<u8>, Vec<Token>) {
    let mut rng = Lcg(seed);
    let mut out: Vec<u8> = Vec::with_capacity(target + 512);
    let mut tokens: Vec<Token> = Vec::new();
    while out.len() < target {
        // One match every ~24 tokens: enough that the length/distance decoders
        // and `extend_from_within` are on the measured path, sparse enough that
        // literal decoding still dominates, as it does for real image data.
        if out.len() > 4096 && rng.next().is_multiple_of(24) {
            let dist = 1 + (rng.next() % 4000).min(out.len() as u32 - 1);
            let len = 3 + rng.next() % 256;
            let (len, dist) = (len.min(258) as u16, dist as u16);
            let start = out.len() - dist as usize;
            for i in 0..len as usize {
                let b = out[start + i];
                out.push(b);
            }
            tokens.push(Token::Match(len, dist));
        } else {
            let b = if rng.next() % 100 < hot_share {
                // The 62 "hot" values: byte 0..61, which the dynamic lane's
                // priority list gives codes of 9 bits or fewer.
                (rng.next() % 62) as u8
            } else {
                62 + (rng.next() % 194) as u8
            };
            out.push(b);
            tokens.push(Token::Literal(b));
        }
    }
    (out, tokens)
}

// ---------------------------------------------------------------------------
// Block emitters
// ---------------------------------------------------------------------------

/// RFC 1951 3.2.6 fixed literal/length code lengths.
fn fixed_lit_lengths() -> Vec<u16> {
    (0..288)
        .map(|sym| match sym {
            0..=143 => 8u16,
            144..=255 => 9,
            256..=279 => 7,
            _ => 8,
        })
        .collect()
}

/// The dynamic lane's literal/length code. Tiers sum to Kraft 1 over exactly
/// 286 symbols and span 3..13 bits, so the stream contains both table-resolvable
/// codes (<= 9 bits) and fallback codes (> 9 bits).
fn dynamic_lit_code() -> CanonCode {
    // 4/8 + 8/32 + 16/128 + 2/256 + 32/512 + 64/2048 + 32/4096 + 128/8192 == 1.
    const TIERS: [(usize, u16); 8] = [
        (4, 3),
        (8, 5),
        (16, 7),
        (2, 8),
        (32, 9),
        (64, 11),
        (32, 12),
        (128, 13),
    ];
    // Priority: the 62 hot byte values first, then end-of-block and the
    // length codes the generator actually emits, then everything else.
    let mut priority: Vec<usize> = (0..62).collect();
    priority.push(256);
    priority.extend(257..286);
    priority.extend(62..256);
    assert_eq!(priority.len(), 286);
    CanonCode::build(lengths_from_tiers(286, &TIERS, &priority))
}

/// The dynamic lane's distance code: 2/4 + 4/16 + 8/64 + 16/128 == 1 over
/// exactly 30 symbols, longest word 7 bits — every distance is a table hit,
/// which is also true of real dynamic blocks.
fn dynamic_dist_code() -> CanonCode {
    const TIERS: [(usize, u16); 4] = [(2, 2), (4, 4), (8, 6), (16, 7)];
    let priority: Vec<usize> = (0..30).collect();
    CanonCode::build(lengths_from_tiers(30, &TIERS, &priority))
}

/// Encode the literal/length + distance code lengths with a code-length code,
/// emitting every length literally (no 16/17/18 run codes). The code-length
/// code's own lengths ride in 3-bit fields, so it must have no word longer than
/// 7 bits — the tier spec below tops out at 4.
fn write_dynamic_header(w: &mut BitWriter, lit: &CanonCode, dist: &CanonCode) -> CanonCode {
    let mut used: Vec<usize> = lit
        .lengths
        .iter()
        .chain(dist.lengths.iter())
        .map(|&l| l as usize)
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect();
    used.sort_unstable();
    // 1/4 + 2/8 + 8/16 == 1 over 11 symbols, longest word 4 bits.
    assert_eq!(
        used.len(),
        11,
        "the code-length tier spec is written for exactly 11 distinct lengths"
    );
    const TIERS: [(usize, u16); 3] = [(1, 2), (2, 3), (8, 4)];
    let cl = CanonCode::build(lengths_from_tiers(19, &TIERS, &used));

    w.bits_lsb(286 - 257, 5); // HLIT
    w.bits_lsb(30 - 1, 5); // HDIST
    w.bits_lsb(19 - 4, 4); // HCLEN
    for &slot in &CLCL_ORDER {
        w.bits_lsb(u32::from(cl.lengths[slot]), 3);
    }
    for &l in lit.lengths.iter().chain(dist.lengths.iter()) {
        cl.put(w, l as usize);
    }
    cl
}

fn write_tokens(w: &mut BitWriter, tokens: &[Token], lit: &CanonCode, dist: &CanonCode) {
    for tok in tokens {
        match *tok {
            Token::Literal(b) => lit.put(w, b as usize),
            Token::Match(len, d) => {
                let li = LENGTH_BASE
                    .iter()
                    .rposition(|&b| b <= len)
                    .expect("length below the smallest base");
                lit.put(w, 257 + li);
                w.bits_lsb(u32::from(len - LENGTH_BASE[li]), LENGTH_EXTRA[li]);
                let di = DIST_BASE
                    .iter()
                    .rposition(|&b| b <= d)
                    .expect("distance below the smallest base");
                dist.put(w, di);
                w.bits_lsb(u32::from(d - DIST_BASE[di]), DIST_EXTRA[di]);
            }
        }
    }
}

fn adler32(data: &[u8]) -> u32 {
    let (mut a, mut b) = (1u32, 0u32);
    for chunk in data.chunks(5552) {
        for &byte in chunk {
            a = a.wrapping_add(u32::from(byte));
            b = b.wrapping_add(a);
        }
        a %= 65521;
        b %= 65521;
    }
    (b << 16) | a
}

fn zlib_wrap(deflate: Vec<u8>, plain: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(deflate.len() + 6);
    out.extend_from_slice(&[0x78, 0x9c]); // CM=8, CINFO=7, FCHECK-valid
    out.extend_from_slice(&deflate);
    out.extend_from_slice(&adler32(plain).to_be_bytes());
    out
}

/// One BTYPE=1 (fixed Huffman) block holding the whole token stream.
fn encode_fixed(plain: &[u8], tokens: &[Token]) -> Vec<u8> {
    let lit = CanonCode::build(fixed_lit_lengths());
    let dist = CanonCode::build(vec![5u16; 32]);
    let mut w = BitWriter::empty();
    w.bits_lsb(1, 1); // BFINAL
    w.bits_lsb(1, 2); // BTYPE = 01, fixed
    write_tokens(&mut w, tokens, &lit, &dist);
    lit.put(&mut w, 256);
    zlib_wrap(w.finish(), plain)
}

/// `blocks` BTYPE=2 (dynamic Huffman) blocks, splitting the token stream evenly.
/// One block is the image case; hundreds of tiny blocks is the table-build
/// regression case.
fn encode_dynamic(plain: &[u8], tokens: &[Token], blocks: usize) -> Vec<u8> {
    let lit = dynamic_lit_code();
    let dist = dynamic_dist_code();
    let mut w = BitWriter::empty();
    let per = tokens.len().div_ceil(blocks.max(1));
    let chunks: Vec<&[Token]> = tokens.chunks(per.max(1)).collect();
    for (i, chunk) in chunks.iter().enumerate() {
        let last = u32::from(i + 1 == chunks.len());
        w.bits_lsb(last, 1); // BFINAL
        w.bits_lsb(2, 2); // BTYPE = 10, dynamic
        write_dynamic_header(&mut w, &lit, &dist);
        write_tokens(&mut w, chunk, &lit, &dist);
        lit.put(&mut w, 256);
    }
    zlib_wrap(w.finish(), plain)
}

// ---------------------------------------------------------------------------
// Lanes
// ---------------------------------------------------------------------------

struct Workload {
    name: &'static str,
    /// The compressed stream fed to `zlib_decompress`.
    stream: Vec<u8>,
    /// The bytes it must decode to.
    plain: Vec<u8>,
    /// Fraction of emitted Huffman symbols whose code is short enough for the
    /// root table. Computed from the encoder's own code lengths, so it is exact.
    table_hit_share: f64,
    /// Number of DEFLATE blocks — the multiplier on per-table build cost.
    blocks: usize,
}

fn hit_share(tokens: &[Token], lit: &CanonCode, dist: &CanonCode) -> f64 {
    let mut hits = 0usize;
    let mut total = 0usize;
    for tok in tokens {
        let (sym_len, extra) = match *tok {
            Token::Literal(b) => (lit.lengths[b as usize], None),
            Token::Match(len, d) => {
                let li = LENGTH_BASE.iter().rposition(|&b| b <= len).unwrap_or(0);
                let di = DIST_BASE.iter().rposition(|&b| b <= d).unwrap_or(0);
                (lit.lengths[257 + li], Some(dist.lengths[di]))
            }
        };
        total += 1;
        if sym_len <= ROOT_BITS {
            hits += 1;
        }
        if let Some(dl) = extra {
            total += 1;
            if dl <= ROOT_BITS {
                hits += 1;
            }
        }
    }
    hits as f64 / total as f64
}

fn workloads() -> Vec<Workload> {
    let (plain_fixed, tokens_fixed) = generate(1 << 20, 70, 0x1234_5678_9abc_def0);
    let fixed_lit = CanonCode::build(fixed_lit_lengths());
    let fixed_dist = CanonCode::build(vec![5u16; 32]);
    let fixed = Workload {
        name: "fixed_1mib",
        stream: encode_fixed(&plain_fixed, &tokens_fixed),
        table_hit_share: hit_share(&tokens_fixed, &fixed_lit, &fixed_dist),
        plain: plain_fixed,
        blocks: 1,
    };

    let (plain_dyn, tokens_dyn) = generate(4 << 20, 70, 0x0fed_cba9_8765_4321);
    let dyn_lit = dynamic_lit_code();
    let dyn_dist = dynamic_dist_code();
    let dynamic = Workload {
        name: "dynamic_4mib",
        stream: encode_dynamic(&plain_dyn, &tokens_dyn, 1),
        table_hit_share: hit_share(&tokens_dyn, &dyn_lit, &dyn_dist),
        plain: plain_dyn,
        blocks: 1,
    };

    // ~400 blocks over 256 KiB: ~640 bytes of output per block, so three Huffman
    // tables are built for every few hundred decoded symbols.
    let (plain_tiny, tokens_tiny) = generate(256 << 10, 70, 0x5555_aaaa_3333_cccc);
    let tiny = Workload {
        name: "tiny_dynamic_blocks",
        stream: encode_dynamic(&plain_tiny, &tokens_tiny, 400),
        table_hit_share: hit_share(&tokens_tiny, &dyn_lit, &dyn_dist),
        plain: plain_tiny,
        blocks: 400,
    };

    vec![fixed, dynamic, tiny]
}

/// Prove each lane decodes to EXACTLY its source (so the hand-written encoder is
/// not quietly producing a stream that errors out after four symbols), and prove
/// the table-hit split each lane was designed for.
///
/// Two-sided on the thing under test: `fixed_1mib` must be ALL table hits (the
/// fixed alphabet's longest code is exactly ROOT_BITS), while `dynamic_4mib`
/// must be a genuine MIX — if it ever became all-hits or all-fallback it would
/// stop bracketing the change and start measuring one half of it.
fn verify_reaches_target(w: &Workload) {
    let decoded = zlib_decompress(&w.stream, 32 << 20)
        .unwrap_or_else(|e| panic!("{}: the generated stream does not decode: {e:?}", w.name));
    assert_eq!(
        decoded.len(),
        w.plain.len(),
        "{}: decoded length differs from the source",
        w.name
    );
    assert!(
        decoded == w.plain,
        "{}: decoded bytes differ from the source — the encoder is wrong and \
         this lane measures nothing meaningful",
        w.name
    );
    match w.name {
        "fixed_1mib" => assert!(
            w.table_hit_share > 0.999,
            "{}: table-hit share is {:.3}, but the fixed alphabet's longest code \
             is exactly ROOT_BITS so every symbol must resolve in the table",
            w.name,
            w.table_hit_share
        ),
        _ => assert!(
            (0.50..0.90).contains(&w.table_hit_share),
            "{}: table-hit share is {:.3} — this lane must exercise BOTH the \
             table and the bit-at-a-time fallback, or it measures only half the \
             change",
            w.name,
            w.table_hit_share
        ),
    }
    assert!(
        w.blocks == 1 || w.blocks >= 100,
        "{}: the block-count lanes must be far apart to separate per-symbol \
         decode cost from per-table build cost",
        w.name
    );
}

fn inflate_zlib(c: &mut Criterion) {
    let mut group = c.benchmark_group("inflate_zlib");
    group.sample_size(20);
    for w in workloads() {
        verify_reaches_target(&w);
        group.throughput(Throughput::Bytes(w.plain.len() as u64));
        group.bench_with_input(BenchmarkId::from_parameter(w.name), &w, |b, w| {
            b.iter(|| {
                let out = zlib_decompress(black_box(&w.stream), 32 << 20);
                let _ = black_box(out.map(|v| v.len()));
            });
        });
    }
    group.finish();
}

criterion_group!(benches, inflate_zlib);
criterion_main!(benches);
