// Copyright 2026 Andrew Yates
// SPDX-License-Identifier: Apache-2.0

//! The airtight owner→client proof: keys generated by `atpkg-keys` sign a full release
//! (root-signed `index.toml` + release-key-signed `pkg.toml` + a real `.tar.zst`), and the
//! ACTUAL client orchestration (`atpkg::flow::install`) installs it — exercising the whole
//! pipeline (verify-select → reachability → gate → verify_pkg → anti-replay → artifact →
//! sha256 → extract → tree_root → activate → shim) with REAL Ed25519 keys, no network.

// Both sides of this proof are unix-gated crates (`atpkg` and `atpkg-keys` each
// compile empty on Windows behind `#![cfg(unix)]`), so the proof is too.
#![cfg(unix)]

use std::collections::HashMap;
use std::io::Write as _;
use std::path::{Path, PathBuf};

use atpkg::Candidate;
use atpkg::flow::{Fetcher, InstallRequest};

const TRIPLE: &str = "aarch64-apple-darwin";

fn scratch(label: &str) -> PathBuf {
    let d = std::env::temp_dir().join(format!("atpkg-o2c-{label}-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&d);
    std::fs::create_dir_all(&d).unwrap();
    d
}

/// A raw USTAR + zstd archive holding `bin/ay`.
fn make_archive(dir: &Path) -> PathBuf {
    let content = b"#!/bin/true\nthe ay binary";
    let mut h = [0u8; 512];
    h[..6].copy_from_slice(b"bin/ay");
    h[100..108].copy_from_slice(b"0000755\0");
    h[108..116].copy_from_slice(b"0000000\0");
    h[116..124].copy_from_slice(b"0000000\0");
    h[124..136].copy_from_slice(format!("{:011o}\0", content.len()).as_bytes());
    h[136..148].copy_from_slice(b"00000000000\0");
    h[148..156].copy_from_slice(b"        ");
    h[156] = b'0';
    h[257..263].copy_from_slice(b"ustar\0");
    h[263..265].copy_from_slice(b"00");
    let sum: u32 = h.iter().map(|&b| u32::from(b)).sum();
    h[148..156].copy_from_slice(format!("{sum:06o}\0 ").as_bytes());
    let mut tar = h.to_vec();
    tar.extend_from_slice(content);
    tar.resize(tar.len() + (512 - content.len() % 512) % 512, 0);
    tar.resize(tar.len() + 1024, 0);
    let path = dir.join("ay-18.tar.zst");
    let f = std::fs::File::create(&path).unwrap();
    let mut enc = zstd::Encoder::new(f, 0).unwrap();
    enc.write_all(&tar).unwrap();
    enc.finish().unwrap();
    path
}

struct Fake {
    index: (Vec<u8>, Vec<u8>),
    pkg: HashMap<(String, u64), (Vec<u8>, Vec<u8>)>,
    archives: HashMap<String, PathBuf>,
}
impl Fetcher for Fake {
    fn index_candidates(&self) -> Result<Vec<Candidate>, String> {
        Ok(vec![Candidate {
            label: "v0".into(),
            index_bytes: self.index.0.clone(),
            sig: self.index.1.clone(),
        }])
    }
    fn pkg_manifest(
        &self,
        _repo: &str,
        program: &str,
        build: u64,
    ) -> Result<(Vec<u8>, Vec<u8>), String> {
        self.pkg
            .get(&(program.to_string(), build))
            .cloned()
            .ok_or_else(|| "no manifest".into())
    }
    fn download(&self, _repo: &str, asset: &str, dest: &Path) -> Result<(), String> {
        let src = self.archives.get(asset).ok_or("no asset")?;
        std::fs::copy(src, dest)
            .map(|_| ())
            .map_err(|e| e.to_string())
    }
}

#[test]
fn owner_signed_release_installs_via_the_real_client_flow() {
    let dir = scratch("e2e");

    // 1. The owner generates the offline ROOT and rotatable RELEASE keys with atpkg-keys.
    let (root_key, root_pub) = atpkg_keys::generate().unwrap();
    let (release_key, release_pub) = atpkg_keys::generate().unwrap();

    // 2. Build + measure the artifact exactly as the publish pipeline does.
    let archive = make_archive(&dir);
    let sha = atpkg::sha256_file(&archive).unwrap();
    let probe = dir.join("probe");
    atpkg::extract_tar_zst(&archive, &probe, 10_000_000, 10_000).unwrap();
    let tree = atpkg::tree_root(&probe).unwrap();

    // 3. Generate + sign the per-build manifest (RELEASE key) and the index (ROOT key).
    let pkg_body = format!(
        "schema = 1\nprogram = \"ay\"\nversion = \"0.1\"\nbuild_number = 18\nexposes = [\"ay\"]\n\
         [[artifact]]\ntarget = \"{TRIPLE}\"\nkind = \"binary\"\nasset = \"ay-18.tar.zst\"\n\
         sha256 = \"{sha}\"\ntree_root = \"{tree}\"\nsize = 100\n\
         [artifact.cost]\ndisk_installed = 1048576\n"
    );
    let pkg_sig = atpkg_keys::sign(&release_key, pkg_body.as_bytes()).unwrap();

    let index_body = format!(
        "schema = 1\nindex_build = 41\nvalid_until = \"2099-01-01T00:00:00Z\"\n\
         [keys]\nrelease_key_id = \"rk\"\nrelease_key_pubkey = \"{release_pub}\"\n\
         [programs.ay]\nrepo = \"ay\"\n\
         [[channels]]\nname = \"stable\"\nchannel_build = 1\nmin_build = 0\npin = {{ ay = 18 }}\n"
    );
    let index_sig = atpkg_keys::sign(&root_key, index_body.as_bytes()).unwrap();

    // 4. Serve them through a fake fetcher and run the REAL client install.
    let mut pkg = HashMap::new();
    pkg.insert(("ay".to_string(), 18u64), (pkg_body.into_bytes(), pkg_sig));
    let mut archives = HashMap::new();
    archives.insert("ay-18.tar.zst".to_string(), archive);
    let fake = Fake {
        index: (index_body.into_bytes(), index_sig),
        pkg,
        archives,
    };
    let layout = atpkg::store::Layout {
        prefix: dir.join("prefix"),
    };
    let req = InstallRequest {
        channel: "stable",
        program: "ay",
        triple: TRIPLE,
        installed: None,
    };

    // now=0 (1970) is comfortably within the 2099 freshness window.
    let report = atpkg::install(&fake, &layout, &root_pub, &req, 0, 0)
        .expect("owner-signed release installs via the real client flow");
    assert_eq!(report.build, 18);
    assert_eq!(report.shimmed, vec!["ay".to_string()]);
    // The binary is staged, shimmed, and active.
    assert_eq!(
        atpkg::which(&layout, "ay").unwrap(),
        layout.build_dir("ay", 18).join("bin/ay")
    );

    // 5. A different root key (attacker) finds NO trusted index — the install is refused.
    let (_other_key, other_pub) = atpkg_keys::generate().unwrap();
    let layout2 = atpkg::store::Layout {
        prefix: dir.join("prefix2"),
    };
    assert!(
        atpkg::install(&fake, &layout2, &other_pub, &req, 0, 0).is_err(),
        "a release not signed by the pinned root must not install"
    );

    let _ = std::fs::remove_dir_all(&dir);
}
