// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Andrew Yates
//
// @generated by: cargo run -p aterm-effects --example gen_dog_glyphs
//
// DO NOT EDIT BY HAND. Regenerated from the breed head asset TOMLs under
// crates/aterm-effects/art/dogs/. The drift test `dog_glyphs_gen_matches_assets`
// fails if this file is stale relative to those assets.
//
// A SEPARATE roster on purpose, exactly like the pet's: every `GlyphKind` row in
// the cat module's `GLYPHS` is a collectible in the GUI's kitty log, whose roster
// cap is pinned to `GLYPH_IDS.len()` — dog heads must not join that table. Only
// the shape vocabulary is shared: the types below are the cat module's, imported
// rather than redeclared, so one drawlist walker paints every roster.

use aterm_scene::vector::PathSeg;

use crate::cat_glyphs_gen::{GlyphDef, GlyphKind, GlyphRole, Layer, Recolor};

/// The dog roster: every authored breed head, ordered by id. Indexes
/// [`DOG_GLYPHS`]. Not a collectible — the typed-word dog cameo draws one
/// of these per summon; the kitty log never records them.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum DogGlyphId {
    D1Beagle,
    D1Bulldog,
    D1Corgi,
    D1Dachshund,
    D1Dalmatian,
    D1Husky,
    D1Poodle,
    D1Pug,
    D1Retriever,
    D1Shepherd,
}

/// Every breed id in [`DOG_GLYPHS`] order. Pair with `DOG_GLYPHS[i].id` for stable
/// string lookup.
pub const DOG_GLYPH_IDS: &[DogGlyphId] = &[
    DogGlyphId::D1Beagle,
    DogGlyphId::D1Bulldog,
    DogGlyphId::D1Corgi,
    DogGlyphId::D1Dachshund,
    DogGlyphId::D1Dalmatian,
    DogGlyphId::D1Husky,
    DogGlyphId::D1Poodle,
    DogGlyphId::D1Pug,
    DogGlyphId::D1Retriever,
    DogGlyphId::D1Shepherd,
];

/// Every breed head's const drawlist, indexed by [`DogGlyphId`] order.
pub const DOG_GLYPHS: &[GlyphDef] = &[
    // D1Beagle (d1_beagle)
    GlyphDef { id: "d1_beagle", kind: GlyphKind::Head, aspect_x1000: 1176, eye_y: 2048, center_x: 2048, word_top: 4096, layers: &[
        Layer { role: GlyphRole::Outline, recolor: Recolor::Fixed, fill: 0x2B2530, paths: &[
            &[PathSeg::Move(1021,2455),PathSeg::Cubic(804,3247,420,3807,164,3710),PathSeg::Cubic(0,3611,0,2891,97,2102),PathSeg::Cubic(315,1310,699,747,955,846),PathSeg::Cubic(1211,943,1242,1662,1021,2455),PathSeg::Close],
            &[PathSeg::Move(3075,2455),PathSeg::Cubic(3292,3247,3676,3807,3932,3710),PathSeg::Cubic(4096,3611,4096,2891,3999,2102),PathSeg::Cubic(3781,1310,3397,747,3141,846),PathSeg::Cubic(2885,943,2854,1662,3075,2455),PathSeg::Close],
            &[PathSeg::Move(3558,2289),PathSeg::Cubic(3558,3220,2883,3976,2048,3976),PathSeg::Cubic(1213,3976,538,3220,538,2289),PathSeg::Cubic(538,1358,1213,602,2048,602),PathSeg::Cubic(2883,602,3558,1358,3558,2289),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Coat, recolor: Recolor::Coat, fill: 0xC8955C, paths: &[
            &[PathSeg::Move(955,2427),PathSeg::Cubic(753,3156,428,3683,225,3605),PathSeg::Cubic(23,3530,23,2876,223,2150),PathSeg::Cubic(425,1422,750,894,952,973),PathSeg::Cubic(1155,1048,1155,1702,955,2427),PathSeg::Close],
            &[PathSeg::Move(3141,2427),PathSeg::Cubic(3343,3156,3668,3683,3871,3605),PathSeg::Cubic(4073,3530,4073,2876,3873,2150),PathSeg::Cubic(3671,1422,3346,894,3144,973),PathSeg::Cubic(2941,1048,2941,1702,3141,2427),PathSeg::Close],
            &[PathSeg::Move(3456,2289),PathSeg::Cubic(3456,3153,2826,3855,2048,3855),PathSeg::Cubic(1270,3855,640,3153,640,2289),PathSeg::Cubic(640,1425,1270,723,2048,723),PathSeg::Cubic(2826,723,3456,1425,3456,2289),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Pattern, recolor: Recolor::Fixed, fill: 0x8A6242, paths: &[
            &[PathSeg::Move(2918,1024),PathSeg::Cubic(2918,1223,2529,1385,2048,1385),PathSeg::Cubic(1567,1385,1178,1223,1178,1024),PathSeg::Cubic(1178,825,1567,663,2048,663),PathSeg::Cubic(2529,663,2918,825,2918,1024),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Pattern, recolor: Recolor::Fixed, fill: 0xF3EBDF, paths: &[
            &[PathSeg::Move(2662,2891),PathSeg::Cubic(2662,3292,2388,3614,2048,3614),PathSeg::Cubic(1708,3614,1434,3292,1434,2891),PathSeg::Cubic(1434,2491,1708,2168,2048,2168),PathSeg::Cubic(2388,2168,2662,2491,2662,2891),PathSeg::Close],
            &[PathSeg::Move(2278,1566),PathSeg::Cubic(2278,2132,2176,2590,2048,2590),PathSeg::Cubic(1920,2590,1818,2132,1818,1566),PathSeg::Cubic(1818,1000,1920,542,2048,542),PathSeg::Cubic(2176,542,2278,1000,2278,1566),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Muzzle, recolor: Recolor::Fixed, fill: 0xF7E9DE, paths: &[
            &[PathSeg::Move(2816,2952),PathSeg::Cubic(2816,3319,2473,3614,2048,3614),PathSeg::Cubic(1623,3614,1280,3319,1280,2952),PathSeg::Cubic(1280,2584,1623,2289,2048,2289),PathSeg::Cubic(2473,2289,2816,2584,2816,2952),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Blush, recolor: Recolor::Fixed, fill: 0xF2A9B4, paths: &[
            &[PathSeg::Move(1190,2530),PathSeg::Cubic(1190,2620,1093,2696,973,2696),PathSeg::Cubic(852,2696,755,2620,755,2530),PathSeg::Cubic(755,2440,852,2364,973,2364),PathSeg::Cubic(1093,2364,1190,2440,1190,2530),PathSeg::Close],
            &[PathSeg::Move(3341,2530),PathSeg::Cubic(3341,2620,3244,2696,3123,2696),PathSeg::Cubic(3003,2696,2906,2620,2906,2530),PathSeg::Cubic(2906,2440,3003,2364,3123,2364),PathSeg::Cubic(3244,2364,3341,2440,3341,2530),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Eye, recolor: Recolor::Fixed, fill: 0x241F29, paths: &[
            &[PathSeg::Move(1549,2108),PathSeg::Cubic(1549,2259,1462,2379,1357,2379),PathSeg::Cubic(1252,2379,1165,2259,1165,2108),PathSeg::Cubic(1165,1958,1252,1837,1357,1837),PathSeg::Cubic(1462,1837,1549,1958,1549,2108),PathSeg::Close],
            &[PathSeg::Move(2931,2108),PathSeg::Cubic(2931,2259,2844,2379,2739,2379),PathSeg::Cubic(2634,2379,2547,2259,2547,2108),PathSeg::Cubic(2547,1958,2634,1837,2739,1837),PathSeg::Cubic(2844,1837,2931,1958,2931,2108),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Detail, recolor: Recolor::Fixed, fill: 0xFFFFFF, paths: &[
            &[PathSeg::Move(1367,2018),PathSeg::Cubic(1367,2060,1336,2096,1300,2096),PathSeg::Cubic(1265,2096,1234,2060,1234,2018),PathSeg::Cubic(1234,1976,1265,1940,1300,1940),PathSeg::Cubic(1336,1940,1367,1976,1367,2018),PathSeg::Close],
            &[PathSeg::Move(2749,2018),PathSeg::Cubic(2749,2060,2719,2096,2683,2096),PathSeg::Cubic(2647,2096,2616,2060,2616,2018),PathSeg::Cubic(2616,1976,2647,1940,2683,1940),PathSeg::Cubic(2719,1940,2749,1976,2749,2018),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Nose, recolor: Recolor::Fixed, fill: 0x2A2029, paths: &[
            &[PathSeg::Move(2304,2650),PathSeg::Cubic(2304,2768,2189,2861,2048,2861),PathSeg::Cubic(1907,2861,1792,2768,1792,2650),PathSeg::Cubic(1792,2533,1907,2440,2048,2440),PathSeg::Cubic(2189,2440,2304,2533,2304,2650),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Mouth, recolor: Recolor::Fixed, fill: 0x2A2029, paths: &[
            &[PathSeg::Move(1715,3012),PathSeg::Cubic(1864,3012,1864,3283,2048,3283),PathSeg::Cubic(2232,3283,2232,3012,2381,3012),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Detail, recolor: Recolor::Fixed, fill: 0xE87E8E, paths: &[
            &[PathSeg::Move(2240,3238),PathSeg::Cubic(2240,3394,2153,3524,2048,3524),PathSeg::Cubic(1943,3524,1856,3394,1856,3238),PathSeg::Cubic(1856,3081,1943,2952,2048,2952),PathSeg::Cubic(2153,2952,2240,3081,2240,3238),PathSeg::Close],
        ] },
    ] },
    // D1Bulldog (d1_bulldog)
    GlyphDef { id: "d1_bulldog", kind: GlyphKind::Head, aspect_x1000: 1176, eye_y: 2048, center_x: 2048, word_top: 4096, layers: &[
        Layer { role: GlyphRole::Outline, recolor: Recolor::Fixed, fill: 0x2B2530, paths: &[
            &[PathSeg::Move(1075,946),PathSeg::Cubic(1260,1220,1280,1560,1124,1702),PathSeg::Cubic(968,1846,694,1741,512,1464),PathSeg::Cubic(328,1190,307,849,463,708),PathSeg::Cubic(620,563,893,669,1075,946),PathSeg::Close],
            &[PathSeg::Move(3021,946),PathSeg::Cubic(2836,1220,2816,1560,2972,1702),PathSeg::Cubic(3128,1846,3402,1741,3584,1464),PathSeg::Cubic(3768,1190,3789,849,3633,708),PathSeg::Cubic(3476,563,3203,669,3021,946),PathSeg::Close],
            &[PathSeg::Move(3738,2349),PathSeg::Cubic(3738,3214,2982,3915,2048,3915),PathSeg::Cubic(1114,3915,358,3214,358,2349),PathSeg::Cubic(358,1485,1114,783,2048,783),PathSeg::Cubic(2982,783,3738,1485,3738,2349),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Coat, recolor: Recolor::Coat, fill: 0xC8955C, paths: &[
            &[PathSeg::Move(996,1018),PathSeg::Cubic(1144,1241,1172,1506,1062,1608),PathSeg::Cubic(950,1711,740,1614,591,1391),PathSeg::Cubic(443,1169,415,904,525,801),PathSeg::Cubic(637,699,847,795,996,1018),PathSeg::Close],
            &[PathSeg::Move(3100,1018),PathSeg::Cubic(2952,1241,2924,1506,3034,1608),PathSeg::Cubic(3146,1711,3356,1614,3505,1391),PathSeg::Cubic(3653,1169,3681,904,3571,801),PathSeg::Cubic(3459,699,3249,795,3100,1018),PathSeg::Close],
            &[PathSeg::Move(3635,2349),PathSeg::Cubic(3635,3147,2924,3795,2048,3795),PathSeg::Cubic(1172,3795,461,3147,461,2349),PathSeg::Cubic(461,1551,1172,904,2048,904),PathSeg::Cubic(2924,904,3635,1551,3635,2349),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Muzzle, recolor: Recolor::Fixed, fill: 0xF7E9DE, paths: &[
            &[PathSeg::Move(2918,3012),PathSeg::Cubic(2918,3379,2529,3674,2048,3674),PathSeg::Cubic(1567,3674,1178,3379,1178,3012),PathSeg::Cubic(1178,2644,1567,2349,2048,2349),PathSeg::Cubic(2529,2349,2918,2644,2918,3012),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Blush, recolor: Recolor::Fixed, fill: 0xF2A9B4, paths: &[
            &[PathSeg::Move(1190,2530),PathSeg::Cubic(1190,2620,1093,2696,973,2696),PathSeg::Cubic(852,2696,755,2620,755,2530),PathSeg::Cubic(755,2440,852,2364,973,2364),PathSeg::Cubic(1093,2364,1190,2440,1190,2530),PathSeg::Close],
            &[PathSeg::Move(3341,2530),PathSeg::Cubic(3341,2620,3244,2696,3123,2696),PathSeg::Cubic(3003,2696,2906,2620,2906,2530),PathSeg::Cubic(2906,2440,3003,2364,3123,2364),PathSeg::Cubic(3244,2364,3341,2440,3341,2530),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Eye, recolor: Recolor::Fixed, fill: 0x241F29, paths: &[
            &[PathSeg::Move(1446,2108),PathSeg::Cubic(1446,2259,1359,2379,1254,2379),PathSeg::Cubic(1149,2379,1062,2259,1062,2108),PathSeg::Cubic(1062,1958,1149,1837,1254,1837),PathSeg::Cubic(1359,1837,1446,1958,1446,2108),PathSeg::Close],
            &[PathSeg::Move(3034,2108),PathSeg::Cubic(3034,2259,2947,2379,2842,2379),PathSeg::Cubic(2737,2379,2650,2259,2650,2108),PathSeg::Cubic(2650,1958,2737,1837,2842,1837),PathSeg::Cubic(2947,1837,3034,1958,3034,2108),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Detail, recolor: Recolor::Fixed, fill: 0xFFFFFF, paths: &[
            &[PathSeg::Move(1265,2018),PathSeg::Cubic(1265,2060,1234,2096,1198,2096),PathSeg::Cubic(1162,2096,1132,2060,1132,2018),PathSeg::Cubic(1132,1976,1162,1940,1198,1940),PathSeg::Cubic(1234,1940,1265,1976,1265,2018),PathSeg::Close],
            &[PathSeg::Move(2852,2018),PathSeg::Cubic(2852,2060,2821,2096,2785,2096),PathSeg::Cubic(2749,2096,2719,2060,2719,2018),PathSeg::Cubic(2719,1976,2749,1940,2785,1940),PathSeg::Cubic(2821,1940,2852,1976,2852,2018),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Nose, recolor: Recolor::Fixed, fill: 0x2A2029, paths: &[
            &[PathSeg::Move(2304,2650),PathSeg::Cubic(2304,2768,2189,2861,2048,2861),PathSeg::Cubic(1907,2861,1792,2768,1792,2650),PathSeg::Cubic(1792,2533,1907,2440,2048,2440),PathSeg::Cubic(2189,2440,2304,2533,2304,2650),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Mouth, recolor: Recolor::Fixed, fill: 0x2A2029, paths: &[
            &[PathSeg::Move(1357,2952),PathSeg::Cubic(1357,3084,1482,3192,1638,3192),PathSeg::Cubic(1795,3192,1920,3084,1920,2952),PathSeg::Line(1843,2952),PathSeg::Cubic(1843,3036,1751,3102,1638,3102),PathSeg::Cubic(1526,3102,1434,3036,1434,2952),PathSeg::Close],
            &[PathSeg::Move(2176,2952),PathSeg::Cubic(2176,3084,2301,3192,2458,3192),PathSeg::Cubic(2614,3192,2739,3084,2739,2952),PathSeg::Line(2662,2952),PathSeg::Cubic(2662,3036,2570,3102,2458,3102),PathSeg::Cubic(2345,3102,2253,3036,2253,2952),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Detail, recolor: Recolor::Fixed, fill: 0xFFFFFF, paths: &[
            &[PathSeg::Move(1933,3102),PathSeg::Cubic(1933,3186,1892,3253,1843,3253),PathSeg::Cubic(1795,3253,1754,3186,1754,3102),PathSeg::Cubic(1754,3018,1795,2952,1843,2952),PathSeg::Cubic(1892,2952,1933,3018,1933,3102),PathSeg::Close],
            &[PathSeg::Move(2342,3102),PathSeg::Cubic(2342,3186,2301,3253,2253,3253),PathSeg::Cubic(2204,3253,2163,3186,2163,3102),PathSeg::Cubic(2163,3018,2204,2952,2253,2952),PathSeg::Cubic(2301,2952,2342,3018,2342,3102),PathSeg::Close],
        ] },
    ] },
    // D1Corgi (d1_corgi)
    GlyphDef { id: "d1_corgi", kind: GlyphKind::Head, aspect_x1000: 1176, eye_y: 2048, center_x: 2048, word_top: 4096, layers: &[
        Layer { role: GlyphRole::Outline, recolor: Recolor::Fixed, fill: 0x2B2530, paths: &[
            &[PathSeg::Move(502,1729),PathSeg::Cubic(271,840,476,292,791,0),PathSeg::Cubic(1257,9,1690,331,1920,1217),PathSeg::Cubic(1751,1455,755,1813,502,1729),PathSeg::Close],
            &[PathSeg::Move(3594,1729),PathSeg::Cubic(3825,840,3620,292,3305,0),PathSeg::Cubic(2839,9,2406,331,2176,1217),PathSeg::Cubic(2345,1455,3341,1813,3594,1729),PathSeg::Close],
            &[PathSeg::Move(3558,2289),PathSeg::Cubic(3558,3220,2883,3976,2048,3976),PathSeg::Cubic(1213,3976,538,3220,538,2289),PathSeg::Cubic(538,1358,1213,602,2048,602),PathSeg::Cubic(2883,602,3558,1358,3558,2289),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Coat, recolor: Recolor::Coat, fill: 0xC8955C, paths: &[
            &[PathSeg::Move(599,1693),PathSeg::Cubic(394,901,568,413,837,33),PathSeg::Cubic(1242,172,1618,461,1823,1253),PathSeg::Cubic(1677,1464,819,1771,599,1693),PathSeg::Close],
            &[PathSeg::Move(3497,1693),PathSeg::Cubic(3702,901,3528,413,3259,33),PathSeg::Cubic(2854,172,2478,461,2273,1253),PathSeg::Cubic(2419,1464,3277,1771,3497,1693),PathSeg::Close],
            &[PathSeg::Move(3456,2289),PathSeg::Cubic(3456,3153,2826,3855,2048,3855),PathSeg::Cubic(1270,3855,640,3153,640,2289),PathSeg::Cubic(640,1425,1270,723,2048,723),PathSeg::Cubic(2826,723,3456,1425,3456,2289),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::InnerEar, recolor: Recolor::Fixed, fill: 0xEFA3AE, paths: &[
            &[PathSeg::Move(870,1530),PathSeg::Cubic(740,1024,817,723,950,494),PathSeg::Cubic(1167,599,1375,795,1508,1301),PathSeg::Cubic(1436,1428,991,1590,870,1530),PathSeg::Close],
            &[PathSeg::Move(3226,1530),PathSeg::Cubic(3356,1024,3279,723,3146,494),PathSeg::Cubic(2929,599,2721,795,2588,1301),PathSeg::Cubic(2660,1428,3105,1590,3226,1530),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Pattern, recolor: Recolor::Fixed, fill: 0xF3EBDF, paths: &[
            &[PathSeg::Move(2714,3012),PathSeg::Cubic(2714,3445,2417,3795,2048,3795),PathSeg::Cubic(1679,3795,1382,3445,1382,3012),PathSeg::Cubic(1382,2578,1679,2229,2048,2229),PathSeg::Cubic(2417,2229,2714,2578,2714,3012),PathSeg::Close],
            &[PathSeg::Move(2227,1867),PathSeg::Cubic(2227,2301,2148,2650,2048,2650),PathSeg::Cubic(1948,2650,1869,2301,1869,1867),PathSeg::Cubic(1869,1434,1948,1084,2048,1084),PathSeg::Cubic(2148,1084,2227,1434,2227,1867),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Muzzle, recolor: Recolor::Fixed, fill: 0xF7E9DE, paths: &[
            &[PathSeg::Move(2816,2952),PathSeg::Cubic(2816,3319,2473,3614,2048,3614),PathSeg::Cubic(1623,3614,1280,3319,1280,2952),PathSeg::Cubic(1280,2584,1623,2289,2048,2289),PathSeg::Cubic(2473,2289,2816,2584,2816,2952),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Blush, recolor: Recolor::Fixed, fill: 0xF2A9B4, paths: &[
            &[PathSeg::Move(1190,2530),PathSeg::Cubic(1190,2620,1093,2696,973,2696),PathSeg::Cubic(852,2696,755,2620,755,2530),PathSeg::Cubic(755,2440,852,2364,973,2364),PathSeg::Cubic(1093,2364,1190,2440,1190,2530),PathSeg::Close],
            &[PathSeg::Move(3341,2530),PathSeg::Cubic(3341,2620,3244,2696,3123,2696),PathSeg::Cubic(3003,2696,2906,2620,2906,2530),PathSeg::Cubic(2906,2440,3003,2364,3123,2364),PathSeg::Cubic(3244,2364,3341,2440,3341,2530),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Eye, recolor: Recolor::Fixed, fill: 0x241F29, paths: &[
            &[PathSeg::Move(1549,2108),PathSeg::Cubic(1549,2259,1462,2379,1357,2379),PathSeg::Cubic(1252,2379,1165,2259,1165,2108),PathSeg::Cubic(1165,1958,1252,1837,1357,1837),PathSeg::Cubic(1462,1837,1549,1958,1549,2108),PathSeg::Close],
            &[PathSeg::Move(2931,2108),PathSeg::Cubic(2931,2259,2844,2379,2739,2379),PathSeg::Cubic(2634,2379,2547,2259,2547,2108),PathSeg::Cubic(2547,1958,2634,1837,2739,1837),PathSeg::Cubic(2844,1837,2931,1958,2931,2108),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Detail, recolor: Recolor::Fixed, fill: 0xFFFFFF, paths: &[
            &[PathSeg::Move(1367,2018),PathSeg::Cubic(1367,2060,1336,2096,1300,2096),PathSeg::Cubic(1265,2096,1234,2060,1234,2018),PathSeg::Cubic(1234,1976,1265,1940,1300,1940),PathSeg::Cubic(1336,1940,1367,1976,1367,2018),PathSeg::Close],
            &[PathSeg::Move(2749,2018),PathSeg::Cubic(2749,2060,2719,2096,2683,2096),PathSeg::Cubic(2647,2096,2616,2060,2616,2018),PathSeg::Cubic(2616,1976,2647,1940,2683,1940),PathSeg::Cubic(2719,1940,2749,1976,2749,2018),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Nose, recolor: Recolor::Fixed, fill: 0x2A2029, paths: &[
            &[PathSeg::Move(2304,2650),PathSeg::Cubic(2304,2768,2189,2861,2048,2861),PathSeg::Cubic(1907,2861,1792,2768,1792,2650),PathSeg::Cubic(1792,2533,1907,2440,2048,2440),PathSeg::Cubic(2189,2440,2304,2533,2304,2650),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Mouth, recolor: Recolor::Fixed, fill: 0x2A2029, paths: &[
            &[PathSeg::Move(1715,3012),PathSeg::Cubic(1864,3012,1864,3283,2048,3283),PathSeg::Cubic(2232,3283,2232,3012,2381,3012),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Detail, recolor: Recolor::Fixed, fill: 0xE87E8E, paths: &[
            &[PathSeg::Move(2240,3238),PathSeg::Cubic(2240,3394,2153,3524,2048,3524),PathSeg::Cubic(1943,3524,1856,3394,1856,3238),PathSeg::Cubic(1856,3081,1943,2952,2048,2952),PathSeg::Cubic(2153,2952,2240,3081,2240,3238),PathSeg::Close],
        ] },
    ] },
    // D1Dachshund (d1_dachshund)
    GlyphDef { id: "d1_dachshund", kind: GlyphKind::Head, aspect_x1000: 1176, eye_y: 2048, center_x: 2048, word_top: 4096, layers: &[
        Layer { role: GlyphRole::Outline, recolor: Recolor::Fixed, fill: 0x2B2530, paths: &[
            &[PathSeg::Move(1021,2455),PathSeg::Cubic(804,3247,420,3807,164,3710),PathSeg::Cubic(0,3611,0,2891,97,2102),PathSeg::Cubic(315,1310,699,747,955,846),PathSeg::Cubic(1211,943,1242,1662,1021,2455),PathSeg::Close],
            &[PathSeg::Move(3075,2455),PathSeg::Cubic(3292,3247,3676,3807,3932,3710),PathSeg::Cubic(4096,3611,4096,2891,3999,2102),PathSeg::Cubic(3781,1310,3397,747,3141,846),PathSeg::Cubic(2885,943,2854,1662,3075,2455),PathSeg::Close],
            &[PathSeg::Move(3558,2289),PathSeg::Cubic(3558,3153,2883,3855,2048,3855),PathSeg::Cubic(1213,3855,538,3153,538,2289),PathSeg::Cubic(538,1425,1213,723,2048,723),PathSeg::Cubic(2883,723,3558,1425,3558,2289),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Coat, recolor: Recolor::Coat, fill: 0xC8955C, paths: &[
            &[PathSeg::Move(955,2427),PathSeg::Cubic(753,3156,428,3683,225,3605),PathSeg::Cubic(23,3530,23,2876,223,2150),PathSeg::Cubic(425,1422,750,894,952,973),PathSeg::Cubic(1155,1048,1155,1702,955,2427),PathSeg::Close],
            &[PathSeg::Move(3141,2427),PathSeg::Cubic(3343,3156,3668,3683,3871,3605),PathSeg::Cubic(4073,3530,4073,2876,3873,2150),PathSeg::Cubic(3671,1422,3346,894,3144,973),PathSeg::Cubic(2941,1048,2941,1702,3141,2427),PathSeg::Close],
            &[PathSeg::Move(3456,2289),PathSeg::Cubic(3456,3087,2826,3735,2048,3735),PathSeg::Cubic(1270,3735,640,3087,640,2289),PathSeg::Cubic(640,1491,1270,843,2048,843),PathSeg::Cubic(2826,843,3456,1491,3456,2289),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Muzzle, recolor: Recolor::Fixed, fill: 0xF7E9DE, paths: &[
            &[PathSeg::Move(2918,3012),PathSeg::Cubic(2918,3427,2529,3765,2048,3765),PathSeg::Cubic(1567,3765,1178,3427,1178,3012),PathSeg::Cubic(1178,2596,1567,2259,2048,2259),PathSeg::Cubic(2529,2259,2918,2596,2918,3012),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Blush, recolor: Recolor::Fixed, fill: 0xF2A9B4, paths: &[
            &[PathSeg::Move(1190,2530),PathSeg::Cubic(1190,2620,1093,2696,973,2696),PathSeg::Cubic(852,2696,755,2620,755,2530),PathSeg::Cubic(755,2440,852,2364,973,2364),PathSeg::Cubic(1093,2364,1190,2440,1190,2530),PathSeg::Close],
            &[PathSeg::Move(3341,2530),PathSeg::Cubic(3341,2620,3244,2696,3123,2696),PathSeg::Cubic(3003,2696,2906,2620,2906,2530),PathSeg::Cubic(2906,2440,3003,2364,3123,2364),PathSeg::Cubic(3244,2364,3341,2440,3341,2530),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Eye, recolor: Recolor::Fixed, fill: 0x241F29, paths: &[
            &[PathSeg::Move(1549,2108),PathSeg::Cubic(1549,2259,1462,2379,1357,2379),PathSeg::Cubic(1252,2379,1165,2259,1165,2108),PathSeg::Cubic(1165,1958,1252,1837,1357,1837),PathSeg::Cubic(1462,1837,1549,1958,1549,2108),PathSeg::Close],
            &[PathSeg::Move(2931,2108),PathSeg::Cubic(2931,2259,2844,2379,2739,2379),PathSeg::Cubic(2634,2379,2547,2259,2547,2108),PathSeg::Cubic(2547,1958,2634,1837,2739,1837),PathSeg::Cubic(2844,1837,2931,1958,2931,2108),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Detail, recolor: Recolor::Fixed, fill: 0xFFFFFF, paths: &[
            &[PathSeg::Move(1367,2018),PathSeg::Cubic(1367,2060,1336,2096,1300,2096),PathSeg::Cubic(1265,2096,1234,2060,1234,2018),PathSeg::Cubic(1234,1976,1265,1940,1300,1940),PathSeg::Cubic(1336,1940,1367,1976,1367,2018),PathSeg::Close],
            &[PathSeg::Move(2749,2018),PathSeg::Cubic(2749,2060,2719,2096,2683,2096),PathSeg::Cubic(2647,2096,2616,2060,2616,2018),PathSeg::Cubic(2616,1976,2647,1940,2683,1940),PathSeg::Cubic(2719,1940,2749,1976,2749,2018),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Nose, recolor: Recolor::Fixed, fill: 0x2A2029, paths: &[
            &[PathSeg::Move(2355,2711),PathSeg::Cubic(2355,2828,2217,2921,2048,2921),PathSeg::Cubic(1879,2921,1741,2828,1741,2711),PathSeg::Cubic(1741,2593,1879,2500,2048,2500),PathSeg::Cubic(2217,2500,2355,2593,2355,2711),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Mouth, recolor: Recolor::Fixed, fill: 0x2A2029, paths: &[
            &[PathSeg::Move(1715,3102),PathSeg::Cubic(1864,3102,1864,3373,2048,3373),PathSeg::Cubic(2232,3373,2232,3102,2381,3102),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Detail, recolor: Recolor::Fixed, fill: 0xE87E8E, paths: &[
            &[PathSeg::Move(2240,3328),PathSeg::Cubic(2240,3485,2153,3614,2048,3614),PathSeg::Cubic(1943,3614,1856,3485,1856,3328),PathSeg::Cubic(1856,3171,1943,3042,2048,3042),PathSeg::Cubic(2153,3042,2240,3171,2240,3328),PathSeg::Close],
        ] },
    ] },
    // D1Dalmatian (d1_dalmatian)
    GlyphDef { id: "d1_dalmatian", kind: GlyphKind::Head, aspect_x1000: 1176, eye_y: 2048, center_x: 2048, word_top: 4096, layers: &[
        Layer { role: GlyphRole::Outline, recolor: Recolor::Fixed, fill: 0x2B2530, paths: &[
            &[PathSeg::Move(1111,2138),PathSeg::Cubic(888,2786,497,3211,236,3087),PathSeg::Cubic(0,2964,0,2337,161,1690),PathSeg::Cubic(384,1042,778,617,1039,741),PathSeg::Cubic(1303,864,1334,1491,1111,2138),PathSeg::Close],
            &[PathSeg::Move(2985,2138),PathSeg::Cubic(3208,2786,3599,3211,3860,3087),PathSeg::Cubic(4096,2964,4096,2337,3935,1690),PathSeg::Cubic(3712,1042,3318,617,3057,741),PathSeg::Cubic(2793,864,2762,1491,2985,2138),PathSeg::Close],
            &[PathSeg::Move(3558,2289),PathSeg::Cubic(3558,3220,2883,3976,2048,3976),PathSeg::Cubic(1213,3976,538,3220,538,2289),PathSeg::Cubic(538,1358,1213,602,2048,602),PathSeg::Cubic(2883,602,3558,1358,3558,2289),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Coat, recolor: Recolor::Fixed, fill: 0xF2EEE6, paths: &[
            &[PathSeg::Move(1044,2108),PathSeg::Cubic(845,2696,512,3087,302,2988),PathSeg::Cubic(92,2888,84,2334,287,1747),PathSeg::Cubic(486,1160,819,768,1029,867),PathSeg::Cubic(1239,967,1247,1521,1044,2108),PathSeg::Close],
            &[PathSeg::Move(3052,2108),PathSeg::Cubic(3251,2696,3584,3087,3794,2988),PathSeg::Cubic(4004,2888,4012,2334,3809,1747),PathSeg::Cubic(3610,1160,3277,768,3067,867),PathSeg::Cubic(2857,967,2849,1521,3052,2108),PathSeg::Close],
            &[PathSeg::Move(3456,2289),PathSeg::Cubic(3456,3153,2826,3855,2048,3855),PathSeg::Cubic(1270,3855,640,3153,640,2289),PathSeg::Cubic(640,1425,1270,723,2048,723),PathSeg::Cubic(2826,723,3456,1425,3456,2289),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Pattern, recolor: Recolor::Fixed, fill: 0x332C38, paths: &[
            &[PathSeg::Move(1498,1325),PathSeg::Cubic(1498,1416,1423,1491,1331,1491),PathSeg::Cubic(1239,1491,1165,1416,1165,1325),PathSeg::Cubic(1165,1235,1239,1160,1331,1160),PathSeg::Cubic(1423,1160,1498,1235,1498,1325),PathSeg::Close],
            &[PathSeg::Move(2803,1144),PathSeg::Cubic(2803,1220,2739,1280,2662,1280),PathSeg::Cubic(2586,1280,2522,1220,2522,1144),PathSeg::Cubic(2522,1069,2586,1009,2662,1009),PathSeg::Cubic(2739,1009,2803,1069,2803,1144),PathSeg::Close],
            &[PathSeg::Move(3174,1807),PathSeg::Cubic(3174,1891,3105,1958,3021,1958),PathSeg::Cubic(2936,1958,2867,1891,2867,1807),PathSeg::Cubic(2867,1723,2936,1656,3021,1656),PathSeg::Cubic(3105,1656,3174,1723,3174,1807),PathSeg::Close],
            &[PathSeg::Move(1254,2771),PathSeg::Cubic(1254,2846,1198,2906,1126,2906),PathSeg::Cubic(1055,2906,998,2846,998,2771),PathSeg::Cubic(998,2696,1055,2635,1126,2635),PathSeg::Cubic(1198,2635,1254,2696,1254,2771),PathSeg::Close],
            &[PathSeg::Move(2598,3494),PathSeg::Cubic(2598,3569,2534,3629,2458,3629),PathSeg::Cubic(2381,3629,2317,3569,2317,3494),PathSeg::Cubic(2317,3418,2381,3358,2458,3358),PathSeg::Cubic(2534,3358,2598,3418,2598,3494),PathSeg::Close],
            &[PathSeg::Move(1754,723),PathSeg::Cubic(1754,789,1702,843,1638,843),PathSeg::Cubic(1574,843,1523,789,1523,723),PathSeg::Cubic(1523,657,1574,602,1638,602),PathSeg::Cubic(1702,602,1754,657,1754,723),PathSeg::Close],
            &[PathSeg::Move(947,1867),PathSeg::Cubic(947,2018,868,2138,768,2138),PathSeg::Cubic(668,2138,589,2018,589,1867),PathSeg::Cubic(589,1717,668,1596,768,1596),PathSeg::Cubic(868,1596,947,1717,947,1867),PathSeg::Close],
            &[PathSeg::Move(3507,2229),PathSeg::Cubic(3507,2379,3428,2500,3328,2500),PathSeg::Cubic(3228,2500,3149,2379,3149,2229),PathSeg::Cubic(3149,2078,3228,1958,3328,1958),PathSeg::Cubic(3428,1958,3507,2078,3507,2229),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Muzzle, recolor: Recolor::Fixed, fill: 0xF7E9DE, paths: &[
            &[PathSeg::Move(2816,2952),PathSeg::Cubic(2816,3319,2473,3614,2048,3614),PathSeg::Cubic(1623,3614,1280,3319,1280,2952),PathSeg::Cubic(1280,2584,1623,2289,2048,2289),PathSeg::Cubic(2473,2289,2816,2584,2816,2952),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Blush, recolor: Recolor::Fixed, fill: 0xF2A9B4, paths: &[
            &[PathSeg::Move(1190,2530),PathSeg::Cubic(1190,2620,1093,2696,973,2696),PathSeg::Cubic(852,2696,755,2620,755,2530),PathSeg::Cubic(755,2440,852,2364,973,2364),PathSeg::Cubic(1093,2364,1190,2440,1190,2530),PathSeg::Close],
            &[PathSeg::Move(3341,2530),PathSeg::Cubic(3341,2620,3244,2696,3123,2696),PathSeg::Cubic(3003,2696,2906,2620,2906,2530),PathSeg::Cubic(2906,2440,3003,2364,3123,2364),PathSeg::Cubic(3244,2364,3341,2440,3341,2530),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Eye, recolor: Recolor::Fixed, fill: 0x241F29, paths: &[
            &[PathSeg::Move(1549,2108),PathSeg::Cubic(1549,2259,1462,2379,1357,2379),PathSeg::Cubic(1252,2379,1165,2259,1165,2108),PathSeg::Cubic(1165,1958,1252,1837,1357,1837),PathSeg::Cubic(1462,1837,1549,1958,1549,2108),PathSeg::Close],
            &[PathSeg::Move(2931,2108),PathSeg::Cubic(2931,2259,2844,2379,2739,2379),PathSeg::Cubic(2634,2379,2547,2259,2547,2108),PathSeg::Cubic(2547,1958,2634,1837,2739,1837),PathSeg::Cubic(2844,1837,2931,1958,2931,2108),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Detail, recolor: Recolor::Fixed, fill: 0xFFFFFF, paths: &[
            &[PathSeg::Move(1367,2018),PathSeg::Cubic(1367,2060,1336,2096,1300,2096),PathSeg::Cubic(1265,2096,1234,2060,1234,2018),PathSeg::Cubic(1234,1976,1265,1940,1300,1940),PathSeg::Cubic(1336,1940,1367,1976,1367,2018),PathSeg::Close],
            &[PathSeg::Move(2749,2018),PathSeg::Cubic(2749,2060,2719,2096,2683,2096),PathSeg::Cubic(2647,2096,2616,2060,2616,2018),PathSeg::Cubic(2616,1976,2647,1940,2683,1940),PathSeg::Cubic(2719,1940,2749,1976,2749,2018),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Nose, recolor: Recolor::Fixed, fill: 0x2A2029, paths: &[
            &[PathSeg::Move(2304,2650),PathSeg::Cubic(2304,2768,2189,2861,2048,2861),PathSeg::Cubic(1907,2861,1792,2768,1792,2650),PathSeg::Cubic(1792,2533,1907,2440,2048,2440),PathSeg::Cubic(2189,2440,2304,2533,2304,2650),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Mouth, recolor: Recolor::Fixed, fill: 0x2A2029, paths: &[
            &[PathSeg::Move(1715,3012),PathSeg::Cubic(1864,3012,1864,3283,2048,3283),PathSeg::Cubic(2232,3283,2232,3012,2381,3012),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Detail, recolor: Recolor::Fixed, fill: 0xE87E8E, paths: &[
            &[PathSeg::Move(2240,3238),PathSeg::Cubic(2240,3394,2153,3524,2048,3524),PathSeg::Cubic(1943,3524,1856,3394,1856,3238),PathSeg::Cubic(1856,3081,1943,2952,2048,2952),PathSeg::Cubic(2153,2952,2240,3081,2240,3238),PathSeg::Close],
        ] },
    ] },
    // D1Husky (d1_husky)
    GlyphDef { id: "d1_husky", kind: GlyphKind::Head, aspect_x1000: 1176, eye_y: 2048, center_x: 2048, word_top: 4096, layers: &[
        Layer { role: GlyphRole::Outline, recolor: Recolor::Fixed, fill: 0x2B2530, paths: &[
            &[PathSeg::Move(591,1608),PathSeg::Cubic(420,804,617,328,901,0),PathSeg::Cubic(1298,126,1661,440,1833,1244),PathSeg::Cubic(1677,1446,809,1699,591,1608),PathSeg::Close],
            &[PathSeg::Move(3505,1608),PathSeg::Cubic(3676,804,3479,328,3195,0),PathSeg::Cubic(2798,126,2435,440,2263,1244),PathSeg::Cubic(2419,1446,3287,1699,3505,1608),PathSeg::Close],
            &[PathSeg::Move(3558,2289),PathSeg::Cubic(3558,3220,2883,3976,2048,3976),PathSeg::Cubic(1213,3976,538,3220,538,2289),PathSeg::Cubic(538,1358,1213,602,2048,602),PathSeg::Cubic(2883,602,3558,1358,3558,2289),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Coat, recolor: Recolor::Coat, fill: 0xC8955C, paths: &[
            &[PathSeg::Move(689,1578),PathSeg::Cubic(540,870,701,455,940,142),PathSeg::Cubic(1275,286,1582,566,1733,1274),PathSeg::Cubic(1605,1449,873,1662,689,1578),PathSeg::Close],
            &[PathSeg::Move(3407,1578),PathSeg::Cubic(3556,870,3395,455,3156,142),PathSeg::Cubic(2821,286,2514,566,2363,1274),PathSeg::Cubic(2491,1449,3223,1662,3407,1578),PathSeg::Close],
            &[PathSeg::Move(3456,2289),PathSeg::Cubic(3456,3153,2826,3855,2048,3855),PathSeg::Cubic(1270,3855,640,3153,640,2289),PathSeg::Cubic(640,1425,1270,723,2048,723),PathSeg::Cubic(2826,723,3456,1425,3456,2289),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::InnerEar, recolor: Recolor::Fixed, fill: 0xEFA3AE, paths: &[
            &[PathSeg::Move(937,1446),PathSeg::Cubic(842,997,919,738,1037,548),PathSeg::Cubic(1219,651,1390,834,1485,1286),PathSeg::Cubic(1421,1391,1037,1503,937,1446),PathSeg::Close],
            &[PathSeg::Move(3159,1446),PathSeg::Cubic(3254,997,3177,738,3059,548),PathSeg::Cubic(2877,651,2706,834,2611,1286),PathSeg::Cubic(2675,1391,3059,1503,3159,1446),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Pattern, recolor: Recolor::Fixed, fill: 0xF3EBDF, paths: &[
            &[PathSeg::Move(2918,2771),PathSeg::Cubic(2918,3271,2529,3674,2048,3674),PathSeg::Cubic(1567,3674,1178,3271,1178,2771),PathSeg::Cubic(1178,2271,1567,1867,2048,1867),PathSeg::Cubic(2529,1867,2918,2271,2918,2771),PathSeg::Close],
            &[PathSeg::Move(1894,1988),PathSeg::Cubic(1894,2138,1756,2259,1587,2259),PathSeg::Cubic(1418,2259,1280,2138,1280,1988),PathSeg::Cubic(1280,1837,1418,1717,1587,1717),PathSeg::Cubic(1756,1717,1894,1837,1894,1988),PathSeg::Close],
            &[PathSeg::Move(2816,1988),PathSeg::Cubic(2816,2138,2678,2259,2509,2259),PathSeg::Cubic(2340,2259,2202,2138,2202,1988),PathSeg::Cubic(2202,1837,2340,1717,2509,1717),PathSeg::Cubic(2678,1717,2816,1837,2816,1988),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Muzzle, recolor: Recolor::Fixed, fill: 0xF7E9DE, paths: &[
            &[PathSeg::Move(2816,2952),PathSeg::Cubic(2816,3319,2473,3614,2048,3614),PathSeg::Cubic(1623,3614,1280,3319,1280,2952),PathSeg::Cubic(1280,2584,1623,2289,2048,2289),PathSeg::Cubic(2473,2289,2816,2584,2816,2952),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Blush, recolor: Recolor::Fixed, fill: 0xF2A9B4, paths: &[
            &[PathSeg::Move(1190,2530),PathSeg::Cubic(1190,2620,1093,2696,973,2696),PathSeg::Cubic(852,2696,755,2620,755,2530),PathSeg::Cubic(755,2440,852,2364,973,2364),PathSeg::Cubic(1093,2364,1190,2440,1190,2530),PathSeg::Close],
            &[PathSeg::Move(3341,2530),PathSeg::Cubic(3341,2620,3244,2696,3123,2696),PathSeg::Cubic(3003,2696,2906,2620,2906,2530),PathSeg::Cubic(2906,2440,3003,2364,3123,2364),PathSeg::Cubic(3244,2364,3341,2440,3341,2530),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Eye, recolor: Recolor::Fixed, fill: 0x241F29, paths: &[
            &[PathSeg::Move(1549,2108),PathSeg::Cubic(1549,2259,1462,2379,1357,2379),PathSeg::Cubic(1252,2379,1165,2259,1165,2108),PathSeg::Cubic(1165,1958,1252,1837,1357,1837),PathSeg::Cubic(1462,1837,1549,1958,1549,2108),PathSeg::Close],
            &[PathSeg::Move(2931,2108),PathSeg::Cubic(2931,2259,2844,2379,2739,2379),PathSeg::Cubic(2634,2379,2547,2259,2547,2108),PathSeg::Cubic(2547,1958,2634,1837,2739,1837),PathSeg::Cubic(2844,1837,2931,1958,2931,2108),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Detail, recolor: Recolor::Fixed, fill: 0xFFFFFF, paths: &[
            &[PathSeg::Move(1367,2018),PathSeg::Cubic(1367,2060,1336,2096,1300,2096),PathSeg::Cubic(1265,2096,1234,2060,1234,2018),PathSeg::Cubic(1234,1976,1265,1940,1300,1940),PathSeg::Cubic(1336,1940,1367,1976,1367,2018),PathSeg::Close],
            &[PathSeg::Move(2749,2018),PathSeg::Cubic(2749,2060,2719,2096,2683,2096),PathSeg::Cubic(2647,2096,2616,2060,2616,2018),PathSeg::Cubic(2616,1976,2647,1940,2683,1940),PathSeg::Cubic(2719,1940,2749,1976,2749,2018),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Nose, recolor: Recolor::Fixed, fill: 0x2A2029, paths: &[
            &[PathSeg::Move(2304,2650),PathSeg::Cubic(2304,2768,2189,2861,2048,2861),PathSeg::Cubic(1907,2861,1792,2768,1792,2650),PathSeg::Cubic(1792,2533,1907,2440,2048,2440),PathSeg::Cubic(2189,2440,2304,2533,2304,2650),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Mouth, recolor: Recolor::Fixed, fill: 0x2A2029, paths: &[
            &[PathSeg::Move(1715,2952),PathSeg::Cubic(1715,3084,1864,3192,2048,3192),PathSeg::Cubic(2232,3192,2381,3084,2381,2952),PathSeg::Line(2304,2952),PathSeg::Cubic(2304,3036,2189,3102,2048,3102),PathSeg::Cubic(1907,3102,1792,3036,1792,2952),PathSeg::Close],
        ] },
    ] },
    // D1Poodle (d1_poodle)
    GlyphDef { id: "d1_poodle", kind: GlyphKind::Head, aspect_x1000: 1176, eye_y: 2048, center_x: 2048, word_top: 4096, layers: &[
        Layer { role: GlyphRole::Outline, recolor: Recolor::Fixed, fill: 0x2B2530, paths: &[
            &[PathSeg::Move(1254,1988),PathSeg::Cubic(1254,2455,1014,2831,717,2831),PathSeg::Cubic(420,2831,179,2455,179,1988),PathSeg::Cubic(179,1521,420,1144,717,1144),PathSeg::Cubic(1014,1144,1254,1521,1254,1988),PathSeg::Close],
            &[PathSeg::Move(2842,1988),PathSeg::Cubic(2842,2455,3082,2831,3379,2831),PathSeg::Cubic(3676,2831,3917,2455,3917,1988),PathSeg::Cubic(3917,1521,3676,1144,3379,1144),PathSeg::Cubic(3082,1144,2842,1521,2842,1988),PathSeg::Close],
            &[PathSeg::Move(2022,783),PathSeg::Cubic(2022,1081,1782,1325,1485,1325),PathSeg::Cubic(1188,1325,947,1081,947,783),PathSeg::Cubic(947,485,1188,241,1485,241),PathSeg::Cubic(1782,241,2022,485,2022,783),PathSeg::Close],
            &[PathSeg::Move(2637,602),PathSeg::Cubic(2637,919,2373,1175,2048,1175),PathSeg::Cubic(1723,1175,1459,919,1459,602),PathSeg::Cubic(1459,286,1723,30,2048,30),PathSeg::Cubic(2373,30,2637,286,2637,602),PathSeg::Close],
            &[PathSeg::Move(3149,783),PathSeg::Cubic(3149,1081,2908,1325,2611,1325),PathSeg::Cubic(2314,1325,2074,1081,2074,783),PathSeg::Cubic(2074,485,2314,241,2611,241),PathSeg::Cubic(2908,241,3149,485,3149,783),PathSeg::Close],
            &[PathSeg::Move(3558,2289),PathSeg::Cubic(3558,3220,2883,3976,2048,3976),PathSeg::Cubic(1213,3976,538,3220,538,2289),PathSeg::Cubic(538,1358,1213,602,2048,602),PathSeg::Cubic(2883,602,3558,1358,3558,2289),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Coat, recolor: Recolor::Coat, fill: 0xC8955C, paths: &[
            &[PathSeg::Move(1152,1988),PathSeg::Cubic(1152,2388,957,2711,717,2711),PathSeg::Cubic(476,2711,282,2388,282,1988),PathSeg::Cubic(282,1587,476,1265,717,1265),PathSeg::Cubic(957,1265,1152,1587,1152,1988),PathSeg::Close],
            &[PathSeg::Move(2944,1988),PathSeg::Cubic(2944,2388,3139,2711,3379,2711),PathSeg::Cubic(3620,2711,3814,2388,3814,1988),PathSeg::Cubic(3814,1587,3620,1265,3379,1265),PathSeg::Cubic(3139,1265,2944,1587,2944,1988),PathSeg::Close],
            &[PathSeg::Move(1920,783),PathSeg::Cubic(1920,1015,1725,1205,1485,1205),PathSeg::Cubic(1244,1205,1050,1015,1050,783),PathSeg::Cubic(1050,551,1244,361,1485,361),PathSeg::Cubic(1725,361,1920,551,1920,783),PathSeg::Close],
            &[PathSeg::Move(2534,602),PathSeg::Cubic(2534,852,2317,1054,2048,1054),PathSeg::Cubic(1779,1054,1562,852,1562,602),PathSeg::Cubic(1562,352,1779,151,2048,151),PathSeg::Cubic(2317,151,2534,352,2534,602),PathSeg::Close],
            &[PathSeg::Move(3046,783),PathSeg::Cubic(3046,1015,2852,1205,2611,1205),PathSeg::Cubic(2371,1205,2176,1015,2176,783),PathSeg::Cubic(2176,551,2371,361,2611,361),PathSeg::Cubic(2852,361,3046,551,3046,783),PathSeg::Close],
            &[PathSeg::Move(3456,2289),PathSeg::Cubic(3456,3153,2826,3855,2048,3855),PathSeg::Cubic(1270,3855,640,3153,640,2289),PathSeg::Cubic(640,1425,1270,723,2048,723),PathSeg::Cubic(2826,723,3456,1425,3456,2289),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Muzzle, recolor: Recolor::Fixed, fill: 0xF7E9DE, paths: &[
            &[PathSeg::Move(2816,2952),PathSeg::Cubic(2816,3319,2473,3614,2048,3614),PathSeg::Cubic(1623,3614,1280,3319,1280,2952),PathSeg::Cubic(1280,2584,1623,2289,2048,2289),PathSeg::Cubic(2473,2289,2816,2584,2816,2952),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Blush, recolor: Recolor::Fixed, fill: 0xF2A9B4, paths: &[
            &[PathSeg::Move(1190,2530),PathSeg::Cubic(1190,2620,1093,2696,973,2696),PathSeg::Cubic(852,2696,755,2620,755,2530),PathSeg::Cubic(755,2440,852,2364,973,2364),PathSeg::Cubic(1093,2364,1190,2440,1190,2530),PathSeg::Close],
            &[PathSeg::Move(3341,2530),PathSeg::Cubic(3341,2620,3244,2696,3123,2696),PathSeg::Cubic(3003,2696,2906,2620,2906,2530),PathSeg::Cubic(2906,2440,3003,2364,3123,2364),PathSeg::Cubic(3244,2364,3341,2440,3341,2530),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Eye, recolor: Recolor::Fixed, fill: 0x241F29, paths: &[
            &[PathSeg::Move(1549,2108),PathSeg::Cubic(1549,2259,1462,2379,1357,2379),PathSeg::Cubic(1252,2379,1165,2259,1165,2108),PathSeg::Cubic(1165,1958,1252,1837,1357,1837),PathSeg::Cubic(1462,1837,1549,1958,1549,2108),PathSeg::Close],
            &[PathSeg::Move(2931,2108),PathSeg::Cubic(2931,2259,2844,2379,2739,2379),PathSeg::Cubic(2634,2379,2547,2259,2547,2108),PathSeg::Cubic(2547,1958,2634,1837,2739,1837),PathSeg::Cubic(2844,1837,2931,1958,2931,2108),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Detail, recolor: Recolor::Fixed, fill: 0xFFFFFF, paths: &[
            &[PathSeg::Move(1367,2018),PathSeg::Cubic(1367,2060,1336,2096,1300,2096),PathSeg::Cubic(1265,2096,1234,2060,1234,2018),PathSeg::Cubic(1234,1976,1265,1940,1300,1940),PathSeg::Cubic(1336,1940,1367,1976,1367,2018),PathSeg::Close],
            &[PathSeg::Move(2749,2018),PathSeg::Cubic(2749,2060,2719,2096,2683,2096),PathSeg::Cubic(2647,2096,2616,2060,2616,2018),PathSeg::Cubic(2616,1976,2647,1940,2683,1940),PathSeg::Cubic(2719,1940,2749,1976,2749,2018),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Nose, recolor: Recolor::Fixed, fill: 0x2A2029, paths: &[
            &[PathSeg::Move(2304,2650),PathSeg::Cubic(2304,2768,2189,2861,2048,2861),PathSeg::Cubic(1907,2861,1792,2768,1792,2650),PathSeg::Cubic(1792,2533,1907,2440,2048,2440),PathSeg::Cubic(2189,2440,2304,2533,2304,2650),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Mouth, recolor: Recolor::Fixed, fill: 0x2A2029, paths: &[
            &[PathSeg::Move(1715,2952),PathSeg::Cubic(1715,3084,1864,3192,2048,3192),PathSeg::Cubic(2232,3192,2381,3084,2381,2952),PathSeg::Line(2304,2952),PathSeg::Cubic(2304,3036,2189,3102,2048,3102),PathSeg::Cubic(1907,3102,1792,3036,1792,2952),PathSeg::Close],
        ] },
    ] },
    // D1Pug (d1_pug)
    GlyphDef { id: "d1_pug", kind: GlyphKind::Head, aspect_x1000: 1176, eye_y: 2048, center_x: 2048, word_top: 4096, layers: &[
        Layer { role: GlyphRole::Outline, recolor: Recolor::Fixed, fill: 0x2B2530, paths: &[
            &[PathSeg::Move(1075,946),PathSeg::Cubic(1260,1220,1280,1560,1124,1702),PathSeg::Cubic(968,1846,694,1741,512,1464),PathSeg::Cubic(328,1190,307,849,463,708),PathSeg::Cubic(620,563,893,669,1075,946),PathSeg::Close],
            &[PathSeg::Move(3021,946),PathSeg::Cubic(2836,1220,2816,1560,2972,1702),PathSeg::Cubic(3128,1846,3402,1741,3584,1464),PathSeg::Cubic(3768,1190,3789,849,3633,708),PathSeg::Cubic(3476,563,3203,669,3021,946),PathSeg::Close],
            &[PathSeg::Move(3558,2289),PathSeg::Cubic(3558,3186,2883,3915,2048,3915),PathSeg::Cubic(1213,3915,538,3186,538,2289),PathSeg::Cubic(538,1391,1213,663,2048,663),PathSeg::Cubic(2883,663,3558,1391,3558,2289),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Coat, recolor: Recolor::Coat, fill: 0xC8955C, paths: &[
            &[PathSeg::Move(996,1018),PathSeg::Cubic(1144,1241,1172,1506,1062,1608),PathSeg::Cubic(950,1711,740,1614,591,1391),PathSeg::Cubic(443,1169,415,904,525,801),PathSeg::Cubic(637,699,847,795,996,1018),PathSeg::Close],
            &[PathSeg::Move(3100,1018),PathSeg::Cubic(2952,1241,2924,1506,3034,1608),PathSeg::Cubic(3146,1711,3356,1614,3505,1391),PathSeg::Cubic(3653,1169,3681,904,3571,801),PathSeg::Cubic(3459,699,3249,795,3100,1018),PathSeg::Close],
            &[PathSeg::Move(3456,2289),PathSeg::Cubic(3456,3120,2826,3795,2048,3795),PathSeg::Cubic(1270,3795,640,3120,640,2289),PathSeg::Cubic(640,1458,1270,783,2048,783),PathSeg::Cubic(2826,783,3456,1458,3456,2289),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Pattern, recolor: Recolor::Fixed, fill: 0x8A6242, paths: &[
            &[PathSeg::Move(2458,1325),PathSeg::Cubic(2458,1425,2273,1506,2048,1506),PathSeg::Cubic(1823,1506,1638,1425,1638,1325),PathSeg::Cubic(1638,1226,1823,1144,2048,1144),PathSeg::Cubic(2273,1144,2458,1226,2458,1325),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Muzzle, recolor: Recolor::Fixed, fill: 0x4A4048, paths: &[
            &[PathSeg::Move(2739,2952),PathSeg::Cubic(2739,3301,2429,3584,2048,3584),PathSeg::Cubic(1667,3584,1357,3301,1357,2952),PathSeg::Cubic(1357,2602,1667,2319,2048,2319),PathSeg::Cubic(2429,2319,2739,2602,2739,2952),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Blush, recolor: Recolor::Fixed, fill: 0xF2A9B4, paths: &[
            &[PathSeg::Move(1190,2530),PathSeg::Cubic(1190,2620,1093,2696,973,2696),PathSeg::Cubic(852,2696,755,2620,755,2530),PathSeg::Cubic(755,2440,852,2364,973,2364),PathSeg::Cubic(1093,2364,1190,2440,1190,2530),PathSeg::Close],
            &[PathSeg::Move(3341,2530),PathSeg::Cubic(3341,2620,3244,2696,3123,2696),PathSeg::Cubic(3003,2696,2906,2620,2906,2530),PathSeg::Cubic(2906,2440,3003,2364,3123,2364),PathSeg::Cubic(3244,2364,3341,2440,3341,2530),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Eye, recolor: Recolor::Fixed, fill: 0x241F29, paths: &[
            &[PathSeg::Move(1498,2108),PathSeg::Cubic(1498,2259,1411,2379,1306,2379),PathSeg::Cubic(1201,2379,1114,2259,1114,2108),PathSeg::Cubic(1114,1958,1201,1837,1306,1837),PathSeg::Cubic(1411,1837,1498,1958,1498,2108),PathSeg::Close],
            &[PathSeg::Move(2982,2108),PathSeg::Cubic(2982,2259,2895,2379,2790,2379),PathSeg::Cubic(2685,2379,2598,2259,2598,2108),PathSeg::Cubic(2598,1958,2685,1837,2790,1837),PathSeg::Cubic(2895,1837,2982,1958,2982,2108),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Detail, recolor: Recolor::Fixed, fill: 0xFFFFFF, paths: &[
            &[PathSeg::Move(1316,2018),PathSeg::Cubic(1316,2060,1285,2096,1249,2096),PathSeg::Cubic(1213,2096,1183,2060,1183,2018),PathSeg::Cubic(1183,1976,1213,1940,1249,1940),PathSeg::Cubic(1285,1940,1316,1976,1316,2018),PathSeg::Close],
            &[PathSeg::Move(2801,2018),PathSeg::Cubic(2801,2060,2770,2096,2734,2096),PathSeg::Cubic(2698,2096,2668,2060,2668,2018),PathSeg::Cubic(2668,1976,2698,1940,2734,1940),PathSeg::Cubic(2770,1940,2801,1976,2801,2018),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Nose, recolor: Recolor::Fixed, fill: 0x2A2029, paths: &[
            &[PathSeg::Move(2304,2650),PathSeg::Cubic(2304,2768,2189,2861,2048,2861),PathSeg::Cubic(1907,2861,1792,2768,1792,2650),PathSeg::Cubic(1792,2533,1907,2440,2048,2440),PathSeg::Cubic(2189,2440,2304,2533,2304,2650),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Detail, recolor: Recolor::Fixed, fill: 0xE87E8E, paths: &[
            &[PathSeg::Move(2202,3192),PathSeg::Cubic(2202,3316,2132,3418,2048,3418),PathSeg::Cubic(1964,3418,1894,3316,1894,3192),PathSeg::Cubic(1894,3069,1964,2967,2048,2967),PathSeg::Cubic(2132,2967,2202,3069,2202,3192),PathSeg::Close],
        ] },
    ] },
    // D1Retriever (d1_retriever)
    GlyphDef { id: "d1_retriever", kind: GlyphKind::Head, aspect_x1000: 1176, eye_y: 2048, center_x: 2048, word_top: 4096, layers: &[
        Layer { role: GlyphRole::Outline, recolor: Recolor::Fixed, fill: 0x2B2530, paths: &[
            &[PathSeg::Move(1111,2138),PathSeg::Cubic(888,2786,497,3211,236,3087),PathSeg::Cubic(0,2964,0,2337,161,1690),PathSeg::Cubic(384,1042,778,617,1039,741),PathSeg::Cubic(1303,864,1334,1491,1111,2138),PathSeg::Close],
            &[PathSeg::Move(2985,2138),PathSeg::Cubic(3208,2786,3599,3211,3860,3087),PathSeg::Cubic(4096,2964,4096,2337,3935,1690),PathSeg::Cubic(3712,1042,3318,617,3057,741),PathSeg::Cubic(2793,864,2762,1491,2985,2138),PathSeg::Close],
            &[PathSeg::Move(3558,2289),PathSeg::Cubic(3558,3220,2883,3976,2048,3976),PathSeg::Cubic(1213,3976,538,3220,538,2289),PathSeg::Cubic(538,1358,1213,602,2048,602),PathSeg::Cubic(2883,602,3558,1358,3558,2289),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Coat, recolor: Recolor::Coat, fill: 0xC8955C, paths: &[
            &[PathSeg::Move(1044,2108),PathSeg::Cubic(845,2696,512,3087,302,2988),PathSeg::Cubic(92,2888,84,2334,287,1747),PathSeg::Cubic(486,1160,819,768,1029,867),PathSeg::Cubic(1239,967,1247,1521,1044,2108),PathSeg::Close],
            &[PathSeg::Move(3052,2108),PathSeg::Cubic(3251,2696,3584,3087,3794,2988),PathSeg::Cubic(4004,2888,4012,2334,3809,1747),PathSeg::Cubic(3610,1160,3277,768,3067,867),PathSeg::Cubic(2857,967,2849,1521,3052,2108),PathSeg::Close],
            &[PathSeg::Move(3456,2289),PathSeg::Cubic(3456,3153,2826,3855,2048,3855),PathSeg::Cubic(1270,3855,640,3153,640,2289),PathSeg::Cubic(640,1425,1270,723,2048,723),PathSeg::Cubic(2826,723,3456,1425,3456,2289),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Muzzle, recolor: Recolor::Fixed, fill: 0xF7E9DE, paths: &[
            &[PathSeg::Move(2816,2952),PathSeg::Cubic(2816,3319,2473,3614,2048,3614),PathSeg::Cubic(1623,3614,1280,3319,1280,2952),PathSeg::Cubic(1280,2584,1623,2289,2048,2289),PathSeg::Cubic(2473,2289,2816,2584,2816,2952),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Blush, recolor: Recolor::Fixed, fill: 0xF2A9B4, paths: &[
            &[PathSeg::Move(1190,2530),PathSeg::Cubic(1190,2620,1093,2696,973,2696),PathSeg::Cubic(852,2696,755,2620,755,2530),PathSeg::Cubic(755,2440,852,2364,973,2364),PathSeg::Cubic(1093,2364,1190,2440,1190,2530),PathSeg::Close],
            &[PathSeg::Move(3341,2530),PathSeg::Cubic(3341,2620,3244,2696,3123,2696),PathSeg::Cubic(3003,2696,2906,2620,2906,2530),PathSeg::Cubic(2906,2440,3003,2364,3123,2364),PathSeg::Cubic(3244,2364,3341,2440,3341,2530),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Eye, recolor: Recolor::Fixed, fill: 0x241F29, paths: &[
            &[PathSeg::Move(1549,2108),PathSeg::Cubic(1549,2259,1462,2379,1357,2379),PathSeg::Cubic(1252,2379,1165,2259,1165,2108),PathSeg::Cubic(1165,1958,1252,1837,1357,1837),PathSeg::Cubic(1462,1837,1549,1958,1549,2108),PathSeg::Close],
            &[PathSeg::Move(2931,2108),PathSeg::Cubic(2931,2259,2844,2379,2739,2379),PathSeg::Cubic(2634,2379,2547,2259,2547,2108),PathSeg::Cubic(2547,1958,2634,1837,2739,1837),PathSeg::Cubic(2844,1837,2931,1958,2931,2108),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Detail, recolor: Recolor::Fixed, fill: 0xFFFFFF, paths: &[
            &[PathSeg::Move(1367,2018),PathSeg::Cubic(1367,2060,1336,2096,1300,2096),PathSeg::Cubic(1265,2096,1234,2060,1234,2018),PathSeg::Cubic(1234,1976,1265,1940,1300,1940),PathSeg::Cubic(1336,1940,1367,1976,1367,2018),PathSeg::Close],
            &[PathSeg::Move(2749,2018),PathSeg::Cubic(2749,2060,2719,2096,2683,2096),PathSeg::Cubic(2647,2096,2616,2060,2616,2018),PathSeg::Cubic(2616,1976,2647,1940,2683,1940),PathSeg::Cubic(2719,1940,2749,1976,2749,2018),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Nose, recolor: Recolor::Fixed, fill: 0x2A2029, paths: &[
            &[PathSeg::Move(2304,2650),PathSeg::Cubic(2304,2768,2189,2861,2048,2861),PathSeg::Cubic(1907,2861,1792,2768,1792,2650),PathSeg::Cubic(1792,2533,1907,2440,2048,2440),PathSeg::Cubic(2189,2440,2304,2533,2304,2650),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Mouth, recolor: Recolor::Fixed, fill: 0x2A2029, paths: &[
            &[PathSeg::Move(1715,3012),PathSeg::Cubic(1864,3012,1864,3283,2048,3283),PathSeg::Cubic(2232,3283,2232,3012,2381,3012),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Detail, recolor: Recolor::Fixed, fill: 0xE87E8E, paths: &[
            &[PathSeg::Move(2240,3238),PathSeg::Cubic(2240,3394,2153,3524,2048,3524),PathSeg::Cubic(1943,3524,1856,3394,1856,3238),PathSeg::Cubic(1856,3081,1943,2952,2048,2952),PathSeg::Cubic(2153,2952,2240,3081,2240,3238),PathSeg::Close],
        ] },
    ] },
    // D1Shepherd (d1_shepherd)
    GlyphDef { id: "d1_shepherd", kind: GlyphKind::Head, aspect_x1000: 1176, eye_y: 2048, center_x: 2048, word_top: 4096, layers: &[
        Layer { role: GlyphRole::Outline, recolor: Recolor::Fixed, fill: 0x2B2530, paths: &[
            &[PathSeg::Move(591,1608),PathSeg::Cubic(420,804,617,328,901,0),PathSeg::Cubic(1298,126,1661,440,1833,1244),PathSeg::Cubic(1677,1446,809,1699,591,1608),PathSeg::Close],
            &[PathSeg::Move(3505,1608),PathSeg::Cubic(3676,804,3479,328,3195,0),PathSeg::Cubic(2798,126,2435,440,2263,1244),PathSeg::Cubic(2419,1446,3287,1699,3505,1608),PathSeg::Close],
            &[PathSeg::Move(3558,2289),PathSeg::Cubic(3558,3220,2883,3976,2048,3976),PathSeg::Cubic(1213,3976,538,3220,538,2289),PathSeg::Cubic(538,1358,1213,602,2048,602),PathSeg::Cubic(2883,602,3558,1358,3558,2289),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Coat, recolor: Recolor::Coat, fill: 0xC8955C, paths: &[
            &[PathSeg::Move(689,1578),PathSeg::Cubic(540,870,701,455,940,142),PathSeg::Cubic(1275,286,1582,566,1733,1274),PathSeg::Cubic(1605,1449,873,1662,689,1578),PathSeg::Close],
            &[PathSeg::Move(3407,1578),PathSeg::Cubic(3556,870,3395,455,3156,142),PathSeg::Cubic(2821,286,2514,566,2363,1274),PathSeg::Cubic(2491,1449,3223,1662,3407,1578),PathSeg::Close],
            &[PathSeg::Move(3456,2289),PathSeg::Cubic(3456,3153,2826,3855,2048,3855),PathSeg::Cubic(1270,3855,640,3153,640,2289),PathSeg::Cubic(640,1425,1270,723,2048,723),PathSeg::Cubic(2826,723,3456,1425,3456,2289),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::InnerEar, recolor: Recolor::Fixed, fill: 0xEFA3AE, paths: &[
            &[PathSeg::Move(937,1446),PathSeg::Cubic(842,997,919,738,1037,548),PathSeg::Cubic(1219,651,1390,834,1485,1286),PathSeg::Cubic(1421,1391,1037,1503,937,1446),PathSeg::Close],
            &[PathSeg::Move(3159,1446),PathSeg::Cubic(3254,997,3177,738,3059,548),PathSeg::Cubic(2877,651,2706,834,2611,1286),PathSeg::Cubic(2675,1391,3059,1503,3159,1446),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Pattern, recolor: Recolor::Fixed, fill: 0x332C38, paths: &[
            &[PathSeg::Move(3072,1205),PathSeg::Cubic(3072,1470,2614,1687,2048,1687),PathSeg::Cubic(1482,1687,1024,1470,1024,1205),PathSeg::Cubic(1024,940,1482,723,2048,723),PathSeg::Cubic(2614,723,3072,940,3072,1205),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Pattern, recolor: Recolor::Fixed, fill: 0x8A6242, paths: &[
            &[PathSeg::Move(1664,1687),PathSeg::Cubic(1664,1762,1572,1822,1459,1822),PathSeg::Cubic(1347,1822,1254,1762,1254,1687),PathSeg::Cubic(1254,1611,1347,1551,1459,1551),PathSeg::Cubic(1572,1551,1664,1611,1664,1687),PathSeg::Close],
            &[PathSeg::Move(2842,1687),PathSeg::Cubic(2842,1762,2749,1822,2637,1822),PathSeg::Cubic(2524,1822,2432,1762,2432,1687),PathSeg::Cubic(2432,1611,2524,1551,2637,1551),PathSeg::Cubic(2749,1551,2842,1611,2842,1687),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Muzzle, recolor: Recolor::Fixed, fill: 0xF7E9DE, paths: &[
            &[PathSeg::Move(2867,3012),PathSeg::Cubic(2867,3412,2501,3735,2048,3735),PathSeg::Cubic(1595,3735,1229,3412,1229,3012),PathSeg::Cubic(1229,2611,1595,2289,2048,2289),PathSeg::Cubic(2501,2289,2867,2611,2867,3012),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Blush, recolor: Recolor::Fixed, fill: 0xF2A9B4, paths: &[
            &[PathSeg::Move(1190,2530),PathSeg::Cubic(1190,2620,1093,2696,973,2696),PathSeg::Cubic(852,2696,755,2620,755,2530),PathSeg::Cubic(755,2440,852,2364,973,2364),PathSeg::Cubic(1093,2364,1190,2440,1190,2530),PathSeg::Close],
            &[PathSeg::Move(3341,2530),PathSeg::Cubic(3341,2620,3244,2696,3123,2696),PathSeg::Cubic(3003,2696,2906,2620,2906,2530),PathSeg::Cubic(2906,2440,3003,2364,3123,2364),PathSeg::Cubic(3244,2364,3341,2440,3341,2530),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Eye, recolor: Recolor::Fixed, fill: 0x241F29, paths: &[
            &[PathSeg::Move(1549,2108),PathSeg::Cubic(1549,2259,1462,2379,1357,2379),PathSeg::Cubic(1252,2379,1165,2259,1165,2108),PathSeg::Cubic(1165,1958,1252,1837,1357,1837),PathSeg::Cubic(1462,1837,1549,1958,1549,2108),PathSeg::Close],
            &[PathSeg::Move(2931,2108),PathSeg::Cubic(2931,2259,2844,2379,2739,2379),PathSeg::Cubic(2634,2379,2547,2259,2547,2108),PathSeg::Cubic(2547,1958,2634,1837,2739,1837),PathSeg::Cubic(2844,1837,2931,1958,2931,2108),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Detail, recolor: Recolor::Fixed, fill: 0xFFFFFF, paths: &[
            &[PathSeg::Move(1367,2018),PathSeg::Cubic(1367,2060,1336,2096,1300,2096),PathSeg::Cubic(1265,2096,1234,2060,1234,2018),PathSeg::Cubic(1234,1976,1265,1940,1300,1940),PathSeg::Cubic(1336,1940,1367,1976,1367,2018),PathSeg::Close],
            &[PathSeg::Move(2749,2018),PathSeg::Cubic(2749,2060,2719,2096,2683,2096),PathSeg::Cubic(2647,2096,2616,2060,2616,2018),PathSeg::Cubic(2616,1976,2647,1940,2683,1940),PathSeg::Cubic(2719,1940,2749,1976,2749,2018),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Nose, recolor: Recolor::Fixed, fill: 0x2A2029, paths: &[
            &[PathSeg::Move(2304,2650),PathSeg::Cubic(2304,2768,2189,2861,2048,2861),PathSeg::Cubic(1907,2861,1792,2768,1792,2650),PathSeg::Cubic(1792,2533,1907,2440,2048,2440),PathSeg::Cubic(2189,2440,2304,2533,2304,2650),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Mouth, recolor: Recolor::Fixed, fill: 0x2A2029, paths: &[
            &[PathSeg::Move(1715,3012),PathSeg::Cubic(1864,3012,1864,3283,2048,3283),PathSeg::Cubic(2232,3283,2232,3012,2381,3012),PathSeg::Close],
        ] },
        Layer { role: GlyphRole::Detail, recolor: Recolor::Fixed, fill: 0xE87E8E, paths: &[
            &[PathSeg::Move(2240,3238),PathSeg::Cubic(2240,3394,2153,3524,2048,3524),PathSeg::Cubic(1943,3524,1856,3394,1856,3238),PathSeg::Cubic(1856,3081,1943,2952,2048,2952),PathSeg::Cubic(2153,2952,2240,3081,2240,3238),PathSeg::Close],
        ] },
    ] },
];

/// The breed variants the typed-summon picker draws from, uniformly.
pub const DOG_HEADS: &[DogGlyphId] = &[
    DogGlyphId::D1Beagle,
    DogGlyphId::D1Bulldog,
    DogGlyphId::D1Corgi,
    DogGlyphId::D1Dachshund,
    DogGlyphId::D1Dalmatian,
    DogGlyphId::D1Husky,
    DogGlyphId::D1Poodle,
    DogGlyphId::D1Pug,
    DogGlyphId::D1Retriever,
    DogGlyphId::D1Shepherd,
];
